import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, GitCompareArrows, Plus, RefreshCw, ShieldCheck, X } from 'lucide-react';
import { MemoryDeleteDialog } from './MemoryLifecycle';
import { api } from './api';
import { t } from './i18n';
import type { MemoryScope } from './LangMemWorkspace';

const topics:Record<string,string>={explanation:'讲解方式',presentation:'呈现方式',workflow:'工作组织',verification:'核对习惯'};
const states:Record<string,string>={candidate:'候选，尚未生效',active:'已启用',blocked:'已停用并抑制旧来源'};
const jobStates:Record<string,string>={pending:'等待处理',running:'正在处理',retry_wait:'等待自动重试',failed:'处理失败',completed:'已完成',cancelled:'已取消',skipped:'已跳过'};
const reasons:Record<string,string>={candidate_rejected:'此候选已拒绝。',fragment_rejected:'优化片段不符合规则边界，请修改候选。',model_failed:'模型处理失败，请检查记忆模型后重试。',sources_changed:'来源已变化，请重新提出候选。',state_changed:'规则或模型配置已变化，请重新提出或评估。',rule_disabled:'规则已停用，旧任务已取消。',user_cancelled:'你已取消此任务。',profile_paused:'方案切换后等待恢复',worker_recovered:'服务重启后已恢复任务。'};
const checks:Record<string,string>={responses_complete:'评估回答未截断',bounded_fragment:'片段长度受控',control_plane_unchanged:'未改动权限控制',explicit_conditions:'具有适用条件',current_request_first:'当前明确指令优先',source_supported:'有来源支持',condition_bounded:'保留条件，未过度泛化',no_authority_change:'未扩大权限',follows_feedback:'符合反馈',no_regression:'未发现明显回归'};
type Draft={revision:number;scope_kind:string;scope_id:string;topic:string;title:string;instruction:string;applies_when:string;exclusions:string;always_on:boolean;priority:number;feedback:string;episode_ids:string[]};
type Version={rejected:number;sources_current?:boolean;version:number;data:Omit<Draft,'revision'|'feedback'|'episode_ids'>;prompt:string;sources:{kind:string;text:string;id?:string;title?:string;version?:number;basis?:string}[];created:number};
type Report={passed:boolean;current_environment?:boolean;checks:Record<string,boolean>;judge:Record<string,boolean|string>;cases:{id:string;query:string;purpose:string;before:string;after:string;truncated?:boolean}[];suite:string};
type Job={id:string;version:number;kind:string;state:string;reason:string;attempts:number;result:Report|null;created:number};
type Rule={id:string;revision:number;topic:string;state:string;active_version:number|null;versions:Version[];jobs:Job[];history:{action:string;version:number;revision:number;created:number}[]};
type Case={id:string;title:string;outcome:string;basis:string};
const empty=(scope:MemoryScope):Draft=>({revision:0,scope_kind:scope.kind,scope_id:scope.id,topic:'explanation',title:'',instruction:'',applies_when:'',exclusions:'',always_on:false,priority:3,feedback:'',episode_ids:[]});

export function CollaborationRules({space,scope,readOnly,onEpisode,initialId,seedEpisodes=[],onChanged}:{space:string;scope:MemoryScope;readOnly:boolean;onEpisode:(id:string)=>void;initialId?:string;seedEpisodes?:string[];onChanged:()=>void}){
 const [deleting,setDeleting]=useState<string|null>(null);
 const [rows,setRows]=useState<Rule[]>([]),[selected,setSelected]=useState<string|null>(initialId||null),[detail,setDetail]=useState<Rule|null>(null),[version,setVersion]=useState(0);
 const [form,setForm]=useState<Draft|null>(seedEpisodes.length?{...empty(scope),episode_ids:seedEpisodes}:null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0),[cases,setCases]=useState<Case[]>([]),[caseQuery,setCaseQuery]=useState('');
 useEffect(()=>{let live=true,timer:ReturnType<typeof setTimeout>;async function load(){try{const params=new URLSearchParams({scope_kind:scope.kind,scope_id:scope.id});const result=await api<{items:Rule[]}>(`/memory/spaces/${space}/rules?${params}`);if(live)setRows(result.items);if(selected){const value=await api<Rule>(`/memory/rules/${selected}`);if(live)setDetail(value)}}catch(e){if(live)setError((e as Error).message)}finally{if(live)timer=setTimeout(load,3000)}}load();return()=>{live=false;clearTimeout(timer)}},[space,scope.kind,scope.id,selected,revision]);
 useEffect(()=>{setSelected(initialId||null);setDetail(null);setVersion(0)},[initialId,space,scope.kind,scope.id]);
 useEffect(()=>{if(!form)return;let live=true;const timer=setTimeout(async()=>{try{const params=new URLSearchParams({scope_kind:form.scope_kind,scope_id:form.scope_id,q:caseQuery,status:'active'});const result=await api<{items:Case[]}>(`/memory/spaces/${space}/episodes?${params}`);if(live)setCases(result.items.filter(c=>['success','partial'].includes(c.outcome)&&['user_feedback','user_correction'].includes(c.basis)))}catch(e){if(live)setError((e as Error).message)}},200);return()=>{live=false;clearTimeout(timer)}},[!!form,caseQuery,form?.scope_id,space]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();setRevision(v=>v+1);onChanged()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function open(row:Rule){setSelected(row.id);setDetail(row);setVersion(row.versions[0].version)}
 const current=detail?.versions.find(v=>v.version===(version||detail.versions[0].version));
 const active=detail?.versions.find(v=>v.version===detail.active_version);
 const evaluation=detail?.jobs.find(j=>j.kind==='evaluate'&&j.version===current?.version&&j.state==='completed')?.result;
 const pending=detail?.jobs.some(j=>j.version===current?.version&&['pending','running','retry_wait'].includes(j.state));
 async function action(kind:string){if(!detail||!current)return;const result=await api<Rule|{job_id:string}>(`/memory/rules/${detail.id}/${kind}`,{method:'POST',body:JSON.stringify({revision:detail.revision,version:current.version})});if('versions' in result)setDetail(result)}
 const close=()=>{setSelected(null);setDetail(null);setVersion(0);setForm(null);setError('')};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)close()};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[busy]);
 return <section className="collaboration-rules"><div className="episode-intro"><div><h3>{t('协作规则')}</h3><p>{t('保存你希望助手遵循的协作习惯。修改经检查后，由你决定是否启用。')}</p></div><ShieldCheck size={27}/></div>
 <div className="button-row"><button className="primary" disabled={readOnly||busy} onClick={()=>{setForm(empty(scope));setCaseQuery('');setError('')}}><Plus size={15}/>{t('提出协作规则')}</button><button className="secondary" aria-label={t('刷新规则')} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={15}/></button></div>
 <p className="field-hint">{t('常驻规则每轮使用；条件规则只在当前问题与适用条件相关时使用。')}</p>
 {error&&!detail&&!form&&<p className="knowledge-error" role="alert">{error}</p>}
 {!rows.length?<div className="memory-empty"><ShieldCheck size={28}/><h3>{t('还没有协作规则')}</h3><p>{t('例如：讲代码时先给最小示例，再逐步解释。不会自动扫描旧聊天或自动启用规则。')}</p></div>:<div className="episode-grid">{rows.map(row=><article className="episode-card" key={row.id}><div className="memory-card-top"><span className="memory-badge">{t(row.versions[0].data.always_on?'常驻规则':topics[row.topic])}</span><small>{t(row.state==='active'&&row.versions[0].version!==row.active_version?'待启用的修改':states[row.state])}</small></div><h3>{row.versions[0].data.title}</h3><p>{row.versions[0].data.instruction}</p><button className="back-link" onClick={()=>open(row)}>{t('查看与编辑')}</button></article>)}</div>}
 {detail&&current&&!form&&<div className="modal-backdrop"><section className="modal episode-modal" role="dialog" aria-modal="true" aria-label={t('协作规则详情')}><header><div><span className="eyebrow">COLLABORATION RULE</span><h2>{current.data.title}</h2><span className="memory-badge">{t(detail.state==='active'&&current.version!==detail.active_version?'待启用的修改':states[detail.state])}</span></div><button aria-label={t('关闭')} disabled={busy} onClick={close}><X size={18}/></button></header><div className="modal-scroll">
 {error&&<p className="knowledge-error" role="alert">{error}</p>}
 {current.sources_current===false&&<p className="knowledge-error">{t('来源经历已变化，此版本暂停用于回答；请以当前来源重新提出候选。')}</p>}
 {current.rejected>0&&<p className="knowledge-notice">{t('此候选已拒绝，原来的生效版本保持不变。')}</p>}
 {detail.state==='active'&&current.version!==detail.active_version&&<p className="field-hint">{t('已有规则仍然生效，以下是待启用的修改。')}</p>}
 <h3>{t('希望如何协作')}</h3><p>{current.data.instruction}</p><p className="field-hint">{t(current.data.always_on?'常驻规则：每轮都会加入，仍需满足适用条件。':'条件规则：只在当前问题相关时加入。')} · {t('优先级 {0}',current.data.priority||3)}</p><div className="lm-compare"><div><h4>{t('适用条件')}</h4><p>{current.data.applies_when}</p></div><div><h4>{t('排除条件')}</h4><p>{current.data.exclusions||t('未额外指定；当前明确要求仍然优先。')}</p></div></div>
 <div className="button-row"><button className="secondary" disabled={readOnly||busy} onClick={()=>setDeleting(detail.id)}>{t('删除')}</button><button className="secondary" disabled={readOnly||busy||pending||!!current.rejected||!current.prompt} onClick={()=>run(()=>action('evaluate'))}>{t('检查修改')}</button><button className="primary" disabled={readOnly||busy||pending||!!current.rejected||!current.sources_current||!evaluation?.passed||evaluation.current_environment===false||current.version===detail.active_version} onClick={()=>run(()=>action('activate'))}>{t(detail.active_version&&current.version<detail.active_version?'回滚到此版本':detail.state==='blocked'?'恢复此版本':'启用此版本')}</button><button className="secondary" disabled={readOnly||busy||!!current.rejected||current.version===detail.active_version} onClick={()=>run(()=>action('reject'))}>{t('拒绝此候选')}</button><button className="secondary" disabled={readOnly||busy||detail.state==='blocked'} onClick={()=>run(()=>action('disable'))}>{t('停用')}</button><button className="secondary" disabled={readOnly||busy||detail.state==='blocked'} onClick={()=>{setForm({...empty(scope),...current.data,revision:detail.revision});setCaseQuery('')}}>{t('编辑')}</button></div>
 <p className="field-hint">{t('停用立即停止后续注入，并阻止旧来源或同主题候选自动复活。恢复和回滚也需有效评估。')}</p>
 {pending&&<p role="status">{t('正在准备修改，请稍候…')}</p>}
 {evaluation&&<p className={evaluation.passed?'knowledge-notice':'knowledge-error'}>{t(evaluation.passed?'检查通过，可以启用此修改。':'修改未通过检查，请调整内容后重试。')}</p>}
 {evaluation?.current_environment===false&&<p className="knowledge-notice">{t('模型配置或其他生效规则已变化，请重新检查。')}</p>}
 {detail.jobs.some(j=>j.version===current.version&&j.state==='failed')&&<p className="knowledge-error">{t('修改处理失败，请检查记忆引擎配置后重试。')}<button className="secondary" disabled={readOnly||busy} onClick={()=>run(async()=>{for(const j of detail.jobs.filter(j=>j.version===current.version&&j.state==='failed'))await api(`/memory/rule-jobs/${j.id}/retry`,{method:'POST'})})}>{t('重试')}</button></p>}
 <h3>{t('反馈与来源经历')}</h3>{current.sources.map((source,i)=><blockquote key={i}><b>{source.kind==='feedback'?t('明确反馈'):source.title+' · v'+source.version}</b><p>{source.text}</p>{source.id&&<button className="back-link" onClick={()=>onEpisode(source.id!)}>{t('打开来源经历')}</button>}</blockquote>)}
 </div></section></div>}
 {form&&<div className="modal-backdrop"><section className="modal episode-modal" role="dialog" aria-modal="true" aria-label={t('提出协作规则')}><header><h2>{t('提出协作规则')}</h2><button aria-label={t('关闭')} disabled={busy} onClick={()=>setForm(null)}><X size={18}/></button></header><form className="modal-scroll memory-edit-form" onSubmit={e=>{e.preventDefault();run(async()=>{const result=await api<{id:string;version:number}>(`/memory/spaces/${space}/rules`,{method:'POST',body:JSON.stringify(form)});setForm(null);setSelected(result.id);setVersion(result.version);setDetail(await api(`/memory/rules/${result.id}`))})}}>
 <p className="field-hint">{t('保存后会准备一条待启用的规则。请填写希望改进的地方，完成检查后再启用。')}</p>
 <label>{t('规则主题')}<select disabled={!!form.revision} value={form.topic} onChange={e=>setForm({...form,topic:e.target.value})}>{Object.entries(topics).map(([k,v])=><option key={k} value={k}>{t(v)}</option>)}</select></label>
 <label>{t('规则标题')}<input required minLength={2} maxLength={80} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label>
 <label>{t('希望如何协作')}<textarea required minLength={5} maxLength={500} placeholder={t('例如：讲解代码时先给最小可运行示例，再解释关键步骤。')} value={form.instruction} onChange={e=>setForm({...form,instruction:e.target.value})}/></label>
 <label className="check-label"><input type="checkbox" checked={form.always_on} onChange={e=>setForm({...form,always_on:e.target.checked})}/>{t('设为常驻规则')}</label>
 <p className="field-hint">{t(form.always_on?'适合语言、语气等每轮都应使用的习惯。':'默认为条件规则，只在问题与适用条件相关时召回。')}</p>
 <label>{t('召回优先级')}<select value={form.priority} onChange={e=>setForm({...form,priority:Number(e.target.value)})}><option value={1}>{t('低')}</option><option value={3}>{t('普通')}</option><option value={5}>{t('高')}</option></select></label>
 <div className="lm-compare"><label>{t('适用条件')}<textarea required minLength={2} maxLength={200} value={form.applies_when} onChange={e=>setForm({...form,applies_when:e.target.value})}/></label><label>{t('排除条件')}<textarea maxLength={200} value={form.exclusions} onChange={e=>setForm({...form,exclusions:e.target.value})}/></label></div>
 <label>{t('明确反馈')}<textarea maxLength={1000} placeholder={t('描述你希望保留或改进的协作方式；当前填写视为你的明确反馈。')} value={form.feedback} onChange={e=>setForm({...form,feedback:e.target.value})}/></label>
 <details open={!!form.episode_ids.length}><summary>{t('选择来源经历')} · {form.episode_ids.length}</summary><input aria-label={t('搜索来源经历')} placeholder={t('按标题或任务目标搜索')} value={caseQuery} onChange={e=>setCaseQuery(e.target.value)}/><p className="field-hint">{t('只列出有用户结果确认的成功或部分成功经历。仅保存了文件的经历不足以形成规则。')}</p>{cases.map(c=><label className="check-label" key={c.id}><input type="checkbox" checked={form.episode_ids.includes(c.id)} disabled={!form.episode_ids.includes(c.id)&&form.episode_ids.length>=4} onChange={e=>setForm({...form,episode_ids:e.target.checked?[...form.episode_ids,c.id]:form.episode_ids.filter(id=>id!==c.id)})}/>{c.title}</label>)}{form.episode_ids.filter(id=>!cases.some(c=>c.id===id)).map(id=><div key={id}>{t('已选择的来源经历')} <button type="button" onClick={()=>setForm({...form,episode_ids:form.episode_ids.filter(x=>x!==id)})}>{t('移除')}</button></div>)}</details>
 {error&&<p className="knowledge-error" role="alert">{error}</p>}<div className="button-row"><button type="button" className="secondary" disabled={busy} onClick={()=>setForm(null)}><ArrowLeft size={14}/>{t('取消')}</button><button className="primary" disabled={busy||readOnly||(!form.feedback.trim()&&form.episode_ids.length<2)}>{t('保存修改')}</button></div>
 </form></section></div>}
 {deleting&&<MemoryDeleteDialog space={space} id={deleting} onClose={()=>setDeleting(null)} onDeleted={()=>{setDeleting(null);close();setRevision(v=>v+1);onChanged()}}/>}
 </section>;
}
