import { useRef, useState } from 'react';
import { ArrowLeft, FileUp, Plug, Plus, RefreshCw, LoaderCircle, Unplug } from 'lucide-react';
import { api } from './api';
import { t } from './i18n';

export type ConnectorTool = { id:string; name:string; description:string; policy:'disabled'|'read'|'confirm'; read_hint:boolean; idempotency_parameter?:string|null; schema:Record<string,unknown> };
type DependencyStatus={ready:boolean;items:{kind:string;name:string;ready:boolean;message:string;min_version?:string}[]};
export type Connector = { id:string; name:string; transport:'http'|'stdio'; url:string; command:string; args:string[]; timeout:number; status:'connected'|'disconnected'; has_token:boolean; env_keys:string[]; tools:ConnectorTool[];package_id?:string|null;package_version?:string|null;package_description?:string;oauth?:Record<string,unknown>|null;oauth_authorized?:boolean;dependency_status?:DependencyStatus };
export type ConnectorSummary = Pick<Connector,'id'|'name'|'status'|'transport'> & {tools:Pick<ConnectorTool,'id'|'name'|'description'|'policy'|'read_hint'>[]};
type Form = {name:string;transport:'http'|'stdio';url:string;command:string;argsText:string;timeout:number;token:string;envText:string;clear_token:boolean;clear_env:boolean};
type PackagePreview={preview_id:string;id:string;name:string;version:string;description:string;transport:'http'|'stdio';oauth?:Record<string,unknown>|null;dependencies:{skills:{name:string;min_version?:string}[];executables:string[];environment:string[]}};

export function ConnectorCatalog({connectors,onChanged}:{connectors:Connector[];onChanged:()=>Promise<void>}) {
  const [form,setForm]=useState<Form|null>(null);const [editing,setEditing]=useState<Connector|null>(null);
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [removing,setRemoving]=useState<string|null>(null);
  const [packagePreview,setPackagePreview]=useState<PackagePreview|null>(null);const packageInput=useRef<HTMLInputElement>(null);
  const update=(p:Partial<Form>)=>setForm(f=>f?{...f,...p}:f);
  async function act(fn:()=>Promise<unknown>,message='') {setBusy(true);setError('');setNotice('');try{await fn();await onChanged();setNotice(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  function edit(c?:Connector) {setEditing(c || null);setError('');setNotice('');setForm({name:c?.name || '',transport:c?.transport || 'http',url:c?.url || '',command:c?.command || '',argsText:c?.args.join('\n') || '',timeout:c?.timeout || 30,token:'',envText:'',clear_token:false,clear_env:false});}
  async function save() {if(!form)return;await act(async()=>{
    const env:Record<string,string>={};
    if(form.envText.trim())for(const line of form.envText.split('\n').filter(l=>l.trim())) {const i=line.indexOf('=');if(i<1)throw new Error(t('环境变量请使用 NAME=value 格式，每行一个。'));env[line.slice(0,i).trim()]=line.slice(i+1);}
    await api(editing?'/connectors/'+editing.id:'/connectors',{method:editing?'PUT':'POST',body:JSON.stringify({name:form.name,transport:form.transport,url:form.url.trim(),command:form.command.trim(),args:form.argsText.split('\n').filter(l=>l!==''),timeout:form.timeout,token:form.token || null,env:form.envText.trim()?env:null,clear_token:form.clear_token,clear_env:form.clear_env})});setForm(null);
  },t('配置已保存，请连接服务。'));}
  async function previewPackage(file?:File){if(!file)return;await act(async()=>{const body=new FormData();body.append('file',file);setPackagePreview(await api<PackagePreview>('/connectors/packages/preview',{method:'POST',body}));});if(packageInput.current)packageInput.current.value='';}
  async function authorize(c:Connector){await act(async()=>{const value=await api<{authorization_url:string}>('/connectors/'+c.id+'/oauth/start',{method:'POST'});const popup=window.open(value.authorization_url,'workbench-oauth','popup,width=640,height=760');if(!popup)throw new Error(t('浏览器阻止了授权窗口，请允许弹窗后重试。'));await new Promise<void>((resolve,reject)=>{const started=Date.now();const timer=window.setInterval(async()=>{if(Date.now()-started>180000||popup.closed){window.clearInterval(timer);try{const list=await api<Connector[]>('/connectors');if(list.find(x=>x.id===c.id)?.oauth_authorized)resolve();else reject(new Error(t('尚未完成 OAuth 授权。')));}catch(e){reject(e)}}},900);});await onChanged();},t('OAuth 授权已完成。'));}
  return <section className="connector-catalog" aria-label={t('连接器配置')}>
    <input ref={packageInput} type="file" accept=".json,.zip" hidden onChange={e=>previewPackage(e.target.files?.[0])}/>
    {busy && <p className="connector-progress" role="status"><LoaderCircle className="spin" size={15}/>{t('正在处理连接器，请稍候…')}</p>}{error && <div className="skill-error" role="alert">{error}</div>}{notice && <p className="connector-notice" role="status">{notice}</p>}
    {packagePreview?<div className="skill-editor"><button className="back-link" disabled={busy} onClick={()=>setPackagePreview(null)}><ArrowLeft size={15}/>{t('取消安装')}</button><span className="eyebrow">CONNECTOR PACKAGE</span><h2>{packagePreview.name}</h2><p>{packagePreview.description}</p><div className="skill-info-row"><span>{packagePreview.id}</span><span>v{packagePreview.version}</span><span>{packagePreview.transport==='http'?'Streamable HTTP':t('本地 stdio')}</span></div>{packagePreview.oauth&&<p className="skill-detail-note">{t('安装后需要通过 OAuth 连接账号，安装包不包含访问凭据。')}</p>}<h3>{t('安装依赖')}</h3>{!packagePreview.dependencies.skills.length&&!packagePreview.dependencies.executables.length&&!packagePreview.dependencies.environment.length?<p className="skill-detail-hint">{t('没有额外依赖。')}</p>:<ul className="connector-dependencies">{packagePreview.dependencies.skills.map(d=><li key={'s'+d.name}>{t('技能')} · {d.name}{d.min_version?' ≥ '+d.min_version:''}</li>)}{packagePreview.dependencies.executables.map(d=><li key={'x'+d}>{t('本机程序')} · {d}</li>)}{packagePreview.dependencies.environment.map(d=><li key={'e'+d}>{t('环境变量')} · {d}</li>)}</ul>}<div className="button-row"><button className="primary" disabled={busy} onClick={()=>act(async()=>{await api('/connectors/packages/install',{method:'POST',body:JSON.stringify({preview_id:packagePreview.preview_id})});setPackagePreview(null);await onChanged();},t('连接器已安装，请完成依赖和账号配置。'))}>{t('确认安装')}</button></div></div>:form ? <div className="skill-editor"><button className="back-link" disabled={busy} onClick={()=>setForm(null)}><ArrowLeft size={15}/>{t('返回连接器列表')}</button><h2>{t(editing?'编辑连接器':'添加连接器')}</h2><p className="skill-detail-hint">{t('保存只记录配置；连接时才访问服务或启动本地进程。修改后需要重新连接并更新服务能力。')}</p>
      <div className="partner-form-grid"><label className="skill-field">{t('连接器名称')}<input maxLength={80} value={form.name} onChange={e=>update({name:e.target.value})}/></label><label className="skill-field">{t('连接方式')}<select value={form.transport} onChange={e=>update({transport:e.target.value as 'http'|'stdio'})}><option value="http">Streamable HTTP</option><option value="stdio">{t('本地 stdio')}</option></select></label></div>
      {form.transport==='http'?<><label className="skill-field partner-wide">{t('MCP 服务地址')}<input placeholder="https://example.com/mcp" value={form.url} onChange={e=>update({url:e.target.value})}/></label><label className="skill-field partner-wide">{t('Bearer Token（可选）')}<input type="password" autoComplete="new-password" value={form.token} onChange={e=>update({token:e.target.value})} placeholder={editing?.has_token?t('已保存，留空保持不变'):t('无认证时留空')}/></label>{editing?.has_token&&<label className="connector-check"><input type="checkbox" checked={form.clear_token} onChange={e=>update({clear_token:e.target.checked})}/>{t('移除已保存的 Token')}</label>}</>:<><p className="skill-detail-note">{t('本地服务以你的系统权限运行。请选择你信任且已安装的程序；工作台不会自动下载安装。')}</p><label className="skill-field partner-wide">{t('可执行文件绝对路径')}<input placeholder="/absolute/path/to/python" value={form.command} onChange={e=>update({command:e.target.value})}/></label><label className="skill-field partner-wide">{t('启动参数（每行一个，不要加引号）')}<textarea rows={3} value={form.argsText} onChange={e=>update({argsText:e.target.value})}/></label><label className="skill-field partner-wide">{t('环境变量（NAME=value，每行一个）')}<textarea rows={3} autoComplete="off" value={form.envText} onChange={e=>update({envText:e.target.value})} placeholder={t('留空保持已保存值；填写后替换全部自定义变量。')}/></label>{!!editing?.env_keys.length&&<><p className="skill-detail-hint">{t('已配置变量')}：{editing.env_keys.join(', ')}</p><label className="connector-check"><input type="checkbox" checked={form.clear_env} onChange={e=>update({clear_env:e.target.checked})}/>{t('移除已保存的环境变量')}</label></>}</>}
      <label className="skill-field connector-timeout">{t('超时（秒）')}<input type="number" min={2} max={120} value={form.timeout} onChange={e=>update({timeout:Number(e.target.value)})}/></label><p className="skill-detail-hint">{t('密钥不会回显。请把密钥填入 Token 或环境变量，不要写入服务地址、名称或启动参数。')}</p><div className="button-row"><button className="primary" disabled={busy||!form.name.trim()} onClick={save}>{t('保存配置')}</button><button className="secondary" disabled={busy} onClick={()=>setForm(null)}>{t('取消')}</button></div>
    </div>:<><div className="skill-catalog-toolbar"><div className="skill-section-label"><h2>{t('连接你的服务')}</h2><p>{t('接入远程或本地 MCP，让伙伴和对话访问对应服务。')}</p></div><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>packageInput.current?.click()}><FileUp size={16}/>{t('安装连接器')}</button><button className="primary" disabled={busy} onClick={()=>edit()}><Plus size={16}/>{t('手动添加')}</button></div></div>
      {!connectors.length&&<div className="skill-empty"><div><Plug size={30}/></div><h2>{t('还没有配置连接器')}</h2><p>{t('支持 Streamable HTTP 与本地 stdio。添加服务并连接后即可使用。')}</p></div>}
      <div className="connector-list">{connectors.map(c=><article id={'connector-'+c.id} className="connector-card compact-capability-card" key={c.id}><header><span className="tool-icon"><Plug size={16}/></span><div className="compact-card-title"><h3>{c.name}</h3><small>{c.transport==='http'?'Streamable HTTP':t('本地 stdio')}{c.package_version?' · v'+c.package_version:''}</small></div><span className={'skill-badge '+(c.status==='connected'?'connector-connected':'')}>{t(c.status==='connected'?'已连接':'未连接')}</span><details className="compact-card-menu"><summary aria-label={t('更多操作')}>•••</summary><div><button disabled={busy} onClick={()=>edit(c)}>{t('编辑配置')}</button><button disabled={busy} onClick={()=>setRemoving(c.id)}>{t('移除')}</button></div></details></header><p className="compact-card-description">{c.package_description||t(c.status==='connected'?'服务已连接，可在伙伴和对话中使用。':'连接后即可在伙伴和对话中使用。')}</p><p className="connector-endpoint">{c.transport==='http'?c.url:c.command}</p><div className="compact-card-meta"><span>{t('{0} 项服务能力',c.tools.length)}</span><span>{c.oauth?t('OAuth 授权'):t(c.transport==='http'?'远程服务':'本地服务')}</span></div>{c.dependency_status&&!c.dependency_status.ready&&<div className="connector-dependency-guide"><b>{t('完成以下准备后即可连接')}</b>{c.dependency_status.items.filter(i=>!i.ready).slice(0,1).map(i=><p key={i.kind+i.name}>○ {i.name} · {t(i.message)}</p>)}</div>}<footer className="compact-connector-actions">{c.oauth&&!c.oauth_authorized?<button className="secondary" disabled={busy} onClick={()=>authorize(c)}>{t('连接账号')}</button>:<button className="secondary" disabled={busy||c.dependency_status?.ready===false} onClick={()=>act(()=>api('/connectors/'+c.id+'/connect',{method:'POST'}),t('连接成功，服务能力已更新。'))}><RefreshCw size={13}/>{t(c.status==='connected'?'更新':'连接')}</button>}{c.oauth&&c.oauth_authorized&&<button className="skill-text-button" disabled={busy} onClick={()=>authorize(c)}>{t('重新授权')}</button>}{c.status==='connected'&&<button className="skill-text-button" disabled={busy} onClick={()=>act(()=>api('/connectors/'+c.id+'/disconnect',{method:'POST'}))}><Unplug size={13}/>{t('断开')}</button>}<button className="skill-text-button" disabled={busy} onClick={()=>edit(c)}>{t('管理')}</button></footer>{removing===c.id&&<div className="connector-remove"><p>{t('移除后将断开服务并删除认证信息，历史调用记录保留。')}</p><button className="secondary" disabled={busy} onClick={()=>act(async()=>{await api('/connectors/'+c.id,{method:'DELETE'});setRemoving(null);})}>{t('确认移除')}</button><button className="skill-text-button" onClick={()=>setRemoving(null)}>{t('取消')}</button></div>}</article>)}</div>
    </>}
  </section>;
}
