import { useEffect, useState } from 'react';
import { ArrowUpRight, Clock3, FileText, GitMerge, Pencil, RefreshCw, Search, X } from 'lucide-react';
import { MemoryDeleteDialog } from './MemoryLifecycle';
import { api } from './api';
import { t } from './i18n';
import type { MemoryScope } from './LangMemWorkspace';
export const outcomeLabels:Record<string,string>={success:'成功',partial:'部分成功',failure:'失败',unknown:'结果未知'};
const basisLabels:Record<string,string>={user_feedback:'用户反馈',user_correction:'用户纠正',artifact_verified:'仅验证产物保存',tool_step_failed:'工具步骤失败',unconfirmed:'尚无结果证据',merge_needs_review:'合并后待确认'};
const typeLabels:Record<string,string>={learning:'学习',coding:'开发',research:'研究',writing:'写作',general:'通用'};
type Case={id:string;space_id:string;scope_kind:string;scope_id:string;title:string;task_type:string;goal:string;body:{context:string;applicability:string;lessons:{text:string;source_id:string;quote:string}[]};outcome:string;basis:string;version:number;status:string;locked:boolean;created:number;updated:number;merged_into?:string};
type Evidence={id:string;role:string;kind:string;text:string;tool:string;status:string;thread_id:string;run_id:string;created:number;artifact?:{name:string;sha256:string;bytes:number}};
type Detail=Case&{outcome_evidence?:{text:string}|null;events:Evidence[];event_total:number;page:number;changes:{action:string;version:number;reason:string;created:number}[]};
type Job={id:string;task_id:string;thread_id:string;state:string;reason:string;attempts:number;manual:number};
type Page={items:Case[];jobs:Job[];total:number;page:number;paused:boolean};
const jobStates:Record<string,string>={collecting:'正在记录本轮操作',pending:'等待整理',running:'正在整理',retry_wait:'等待自动重试',failed:'需要处理',skipped:'已跳过'};
const jobReasons:Record<string,string>={case_protected:'经历已锁定、归档或合并，未自动覆盖。',manual_state_changed:'来源之后已有人工维护，旧整理未生效。',manual_or_config_changed:'人工维护或配置已变化，旧整理未生效。',config_changed:'配置已变化，旧整理未生效。',engine_failed:'经历整理失败，请检查记忆模型设置后重试。',profile_paused:'方案切换后等待恢复',worker_recovered:'服务重启后已恢复任务。'};
export function EpisodeChatActions({threadId,space,scopeKind='personal',scopeId='personal',busy,onChanged}:{threadId:string;space:string;scopeKind?:string;scopeId?:string;busy:boolean;onChanged:()=>Promise<unknown>}){
 const [saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 async function act(action:string){setSaving(true);setNotice('');setError('');try{const result=await api<{status?:string}>(`/sessions/${threadId}/episodes/${action}`,{method:'POST',body:JSON.stringify({space_id:space,scope_kind:scopeKind,scope_id:scopeId})});setNotice(t(action==='new-task'?'下一轮将开始新的经历；已有经历保留。':result.status==='completed'?'此轮已保存，可在记忆中心查看任务经历。':'当前轮已进入经历整理，不会扫描旧聊天。'));await onChanged()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <div className="episode-chat-actions"><div><button className="secondary" disabled={busy||saving} onClick={()=>act('save')}><FileText size={14}/>{t('保存当前轮为经历')}</button><button className="secondary" disabled={busy||saving} onClick={()=>act('new-task')}>{t('下一轮开始新经历')}</button></div><small>{t('同一任务的后续轮次更新同一经历；更换任务时先开始新经历。')}</small>{notice&&<p role="status">{notice}</p>}{error&&<p className="knowledge-error" role="alert">{error}</p>}</div>;
}
export function Episodes({space,scope,readOnly,onSource,initialId,onProposeRule}:{space:string;scope:MemoryScope;readOnly:boolean;onSource:(id:string)=>void;initialId?:string;onProposeRule?:(id:string)=>void}){
 const [deleting,setDeleting]=useState<string|null>(null);
 const [data,setData]=useState<Page|null>(null),[page,setPage]=useState(1),[q,setQ]=useState(''),[status,setStatus]=useState('active'),[outcome,setOutcome]=useState('');
 const [detail,setDetail]=useState<Detail|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const [editing,setEditing]=useState<{version:number;title:string;context:string;applicability:string;outcome:string;reason:string;locked:boolean}|null>(null);
 const [merging,setMerging]=useState(false),[target,setTarget]=useState(''),[targetQuery,setTargetQuery]=useState(''),[targets,setTargets]=useState<Case[]>([]);
 const [artifact,setArtifact]=useState<{title:string;content:string;matches_saved:boolean}|null>(null);
 const [query,setQuery]=useState(''),[hits,setHits]=useState<{id:string;title:string;outcome:string;basis:string;score:number}[]|null>(null);
 useEffect(()=>{let live=true;let timer:ReturnType<typeof setTimeout>;const load=async()=>{try{const params=new URLSearchParams({scope_kind:scope.kind,scope_id:scope.id,q,status,outcome,page:String(page)});const result=await api<Page>(`/memory/spaces/${space}/episodes?${params}`);if(live)setData(result)}catch(e){if(live)setError((e as Error).message)}finally{if(live)timer=setTimeout(load,3000)}};setData(null);setDetail(null);const first=setTimeout(load,200);return()=>{live=false;clearTimeout(first);clearTimeout(timer)}},[space,scope.id,scope.kind,q,status,outcome,page,revision]);
 useEffect(()=>{if(initialId)run(()=>open(initialId))},[initialId]);
 useEffect(()=>{if(!merging||!detail)return;let live=true;const timer=setTimeout(async()=>{try{const params=new URLSearchParams({scope_kind:detail.scope_kind,scope_id:detail.scope_id,status:'active',q:targetQuery});const result=await api<Page>(`/memory/spaces/${space}/episodes?${params}`);if(live){setTargets(result.items.filter(r=>r.id!==detail.id));setTarget('')}}catch(e){if(live)setError((e as Error).message)}},200);return()=>{live=false;clearTimeout(timer)}},[merging,targetQuery,detail?.id,space]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function open(id:string,page=1){setEditing(null);setMerging(false);setArtifact(null);setDetail(await api(`/memory/episodes/${id}?page=${page}`))}
 async function action(job:Job,kind:string){await api(`/memory/spaces/${space}/episode-jobs/${job.id}/${kind}`,{method:'POST'});setRevision(v=>v+1)}
 function close(){setDetail(null);setEditing(null);setMerging(false);setArtifact(null)}
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)close()};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[busy]);
 const badge=(row:{outcome:string;basis:string})=><span className={'episode-outcome '+row.outcome}>{t(outcomeLabels[row.outcome])} · {t(basisLabels[row.basis])}</span>;
 return <section className="episodes"><div className="episode-intro"><div><h3>{t('任务经历')}</h3><p>{t('记录做过的任务、结果和可复用的经验。')}</p></div><Clock3 size={26}/></div>
 <div className="lm-fact-toolbar"><div className="memory-search"><Search size={16}/><input className="memory-search-input" aria-label={t('搜索任务经历')} placeholder={t('搜索任务经历')} value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></div><select aria-label={t('经历结果')} value={outcome} onChange={e=>{setOutcome(e.target.value);setPage(1)}}><option value="">{t('全部结果')}</option>{Object.entries(outcomeLabels).map(([key,label])=><option key={key} value={key}>{t(label)}</option>)}</select><select aria-label={t('经历状态')} value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}>{[['active','生效中'],['merged','已合并'],['all','全部']].map(([k,v])=><option key={k} value={k}>{t(v)}</option>)}</select><button className="secondary" aria-label={t('刷新经历')} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={15}/></button></div>
 <p className="field-hint">{t('当前空间的任务经历统一管理。没有结果依据的案例保持未知，不自动注入回答。')}</p>
 {error&&<p role="alert" className="knowledge-error">{error}</p>}
 {!data?<p>{t('正在加载…')}</p>:!data.items.length?<div className="memory-empty"><Clock3 size={28}/><h3>{t('这个空间还没有任务经历')}</h3><p>{t('启用自动学习和经历整理后，任务操作与明确反馈会在后台整理为经历。')}</p></div>:<div className="episode-grid">{data.items.map(row=><article className="episode-card" key={row.id}><div className="memory-card-top">{badge(row)}<small>{t(typeLabels[row.task_type])}</small></div><h3>{row.title}</h3><p>{row.body.context||row.goal}</p><div className="episode-card-footer"><time>{new Date(row.updated*1000).toLocaleString()}</time><button className="back-link" onClick={()=>run(()=>open(row.id))}>{t('查看经历')}<ArrowUpRight size={14}/></button></div></article>)}</div>}
 {!!data&&data.total>30&&<div className="button-row"><button disabled={page<=1} onClick={()=>setPage(page-1)}>{t('上一页')}</button><span>{page} / {Math.ceil(data.total/30)}</span><button disabled={page*30>=data.total} onClick={()=>setPage(page+1)}>{t('下一页')}</button></div>}
 {detail&&<div className="modal-backdrop"><section className="modal episode-modal" role="dialog" aria-modal="true" aria-label={t('任务经历详情')}><header><div><span className="eyebrow">TASK EXPERIENCE</span><h2>{detail.title}</h2>{badge(detail)}</div><button disabled={busy} aria-label={t('关闭')} onClick={close}><X size={18}/></button></header><div className="modal-scroll">
 {error&&<p role="alert" className="knowledge-error">{error}</p>}
 {artifact?<><h3>{artifact.title}</h3><p className={artifact.matches_saved?'knowledge-notice':'knowledge-error'}>{t(artifact.matches_saved?'当前产物与保存时指纹一致。':'当前产物已发生变化，以下为当前内容，不能代替当时的结果证据。')}</p><pre className="episode-artifact">{artifact.content}</pre><button onClick={()=>setArtifact(null)}>{t('返回经历')}</button></>:editing?<form className="memory-edit-form" onSubmit={e=>{e.preventDefault();run(async()=>{await api(`/memory/episodes/${detail.id}`,{method:'PUT',body:JSON.stringify(editing)});setEditing(null);await open(detail.id)})}}><label>{t('经历标题')}<input required maxLength={100} value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>{t('任务背景与复盘')}<textarea maxLength={800} value={editing.context} onChange={e=>setEditing({...editing,context:e.target.value})}/></label><label>{t('适用条件')}<textarea maxLength={400} value={editing.applicability} onChange={e=>setEditing({...editing,applicability:e.target.value})}/></label><label>{t('经历结果')}<select value={editing.outcome} onChange={e=>setEditing({...editing,outcome:e.target.value})}>{Object.entries(outcomeLabels).map(([k,v])=><option key={k} value={k}>{t(v)}</option>)}</select></label><label>{t('纠正依据')}<textarea required minLength={2} maxLength={500} placeholder={t('说明你如何确认结果，仍会标识为用户纠正。')} value={editing.reason} onChange={e=>setEditing({...editing,reason:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={editing.locked} onChange={e=>setEditing({...editing,locked:e.target.checked})}/>{t('锁定经历，暂停自动更新')}</label><div className="button-row"><button type="button" onClick={()=>setEditing(null)}>{t('取消')}</button><button className="primary" disabled={busy}>{t('保存纠正')}</button></div></form>:merging?<form onSubmit={e=>{e.preventDefault();run(async()=>{const other=targets.find(r=>r.id===target);if(!other)throw new Error(t('请选择目标经历'));await api(`/memory/episodes/${detail.id}/merge`,{method:'POST',body:JSON.stringify({version:detail.version,target_id:target,target_version:other.version})});await open(target)})}}><p>{t('保留目标摘要和双方来源。合并后结果设为未知并锁定，须重新核对；不会自动选用较乐观的结果。')}</p><label>{t('搜索合并目标')}<input value={targetQuery} onChange={e=>setTargetQuery(e.target.value)} placeholder={t('按标题或任务目标搜索')}/></label><label>{t('合并到另一条经历')}<select required value={target} onChange={e=>setTarget(e.target.value)}><option value="">{t('请选择目标经历')}</option>{targets.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><div className="button-row"><button type="button" onClick={()=>setMerging(false)}>{t('取消')}</button><button className="primary" disabled={!target||busy}>{t('确认合并')}</button></div></form>:<>
 <div className="episode-meta"><span>{t(detail.locked?'已锁定':'自动维护')}</span><span>{t(detail.status==='merged'?'已合并':'生效中')}</span></div><h3>{t('结果依据')}</h3><p>{detail.outcome_evidence?.text||(detail.basis==='user_correction'?detail.changes.find(c=>c.action==='corrected')?.reason:t(basisLabels[detail.basis]))}</p><h3>{t('任务目标')}</h3><p>{detail.goal}</p><h3>{t('任务背景与复盘')}</h3><p>{detail.body.context||t('尚未记录')}</p><h3>{t('适用条件')}</h3><p>{detail.body.applicability||t('尚未记录')}</p>
 {!!detail.body.lessons.length&&<><h3>{t('有依据的简短经验')}</h3>{detail.body.lessons.map((n,i)=><blockquote key={i}><p>{n.text}</p><small>{t('原文依据')}：{n.quote}</small></blockquote>)}</>}
 <div className="button-row"><button className="secondary" disabled={readOnly||busy} onClick={()=>setDeleting(detail.id)}>{t('删除')}</button>{onProposeRule&&detail.status==='active'&&['success','partial'].includes(detail.outcome)&&['user_feedback','user_correction'].includes(detail.basis)&&<button className="secondary" disabled={readOnly||busy} onClick={()=>onProposeRule(detail.id)}>{t('根据经历提出协作规则')}</button>}{detail.status!=='merged'&&<><button className="secondary" disabled={readOnly||busy} onClick={()=>setEditing({version:detail.version,title:detail.title,context:detail.body.context,applicability:detail.body.applicability,outcome:detail.outcome,reason:'',locked:true})}><Pencil size={14}/>{t('纠正经历与结果')}</button>{detail.status==='active'&&<button className="secondary" disabled={readOnly||busy} onClick={()=>{setMerging(true);setTarget('');setTargetQuery('')}}><GitMerge size={14}/>{t('合并同一任务')}</button>}</>}{detail.merged_into&&<button className="secondary" onClick={()=>run(()=>open(detail.merged_into!))}>{t('查看合并后的经历')}</button>}</div>

 </>}
 </div></section></div>}
 {deleting&&<MemoryDeleteDialog space={space} id={deleting} onClose={()=>setDeleting(null)} onDeleted={()=>{setDeleting(null);close();setRevision(v=>v+1)}}/>}
 </section>;
}
