import { CollaborationRules } from './CollaborationRules';
import { useEffect, useState } from 'react';
import { BrainCircuit, Clock3, ListChecks, LockKeyhole, Pencil, Plus, Search, Trash2, UserRound, X } from 'lucide-react';
import { api } from './api';
import { t } from './i18n';
import { Episodes } from './Episodes';

export type MemoryScope = {id:string;space_id:string;kind:'personal'|'project'|'partner';name:string};
type RecordItem = {expired?:boolean;id:string;content:string;category:string;memory_type:'profile'|'fact';profile_key:string;scope_kind:string;scope_id:string;conditions:string;topic_key:string;locked:boolean;manual:boolean;status:string;version:number;source_kind:string;source_quote:string;source_thread:string|null;updated:string};
type ProfileField = {key:string;label:string;description?:string;custom?:boolean;memory:RecordItem|null};
type Page<T> = {items:T[];total:number;page:number};
type Draft = {id?:string;version?:number;content:string;category:string;memory_type:'profile'|'fact';profile_key:string;scope_kind:string;scope_id:string;conditions:string;topic_key:string;locked:boolean};
const categoryLabels:Record<string,string> = {preference:'偏好',fact:'事实',goal:'目标',experience:'经验'};
const fieldLabels:Record<string,string> = {preferred_name:'称呼',language:'交流语言',timezone:'时区',coding_experience:'代码经验',explanation_style:'讲解方式',learning_direction:'长期学习方向'};
function Pagination({page,total,onChange}:{page:number;total:number;onChange:(value:number)=>void}) {
  return total>30 ? <div className="button-row"><button className="secondary" disabled={page<=1} onClick={()=>onChange(page-1)}>{t('上一页')}</button><span>{page} / {Math.ceil(total/30)}</span><button className="secondary" disabled={page*30>=total} onClick={()=>onChange(page+1)}>{t('下一页')}</button></div>:null;
}

export function LangMemWorkspace({readOnly=false,space,refreshKey,onChanged,onSource}:{readOnly?:boolean;space:string;refreshKey:boolean;onChanged:()=>void;onSource:(id:string)=>void}) {
  const [ruleId,setRuleId]=useState<string>();
  const [ruleSeeds,setRuleSeeds]=useState<string[]>([]);
  const [episodeId,setEpisodeId]=useState<string>();
  const [layer,setLayer]=useState<'semantic'|'episodes'|'rules'>('semantic');
  const [view,setView]=useState<'profile'|'facts'>('profile');
  const scope:MemoryScope={id:'personal',kind:'personal',name:'全局',space_id:space};
  const [profile,setProfile]=useState<ProfileField[]>([]);
  const [facts,setFacts]=useState<Record<string,Page<RecordItem>>>({});
  const [categoryPages,setCategoryPages]=useState<Record<string,number>>({});
  const [groupEditor,setGroupEditor]=useState<{category:string;token:string;content:string;originalContent:string}|null>(null);
  const [groupConfirmation,setGroupConfirmation]=useState<{confirmation:string;removed:string[];related:{id:string;kind:string;title:string}[]}|null>(null);
  const [newField,setNewField]=useState<{label:string;description:string;content:string}|null>(null);
  const [query,setQuery]=useState('');const [category,setCategory]=useState('');const status='all';const [page,setPage]=useState(1);
  const [revision,setRevision]=useState(0);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  const [editing,setEditing]=useState<Draft|null>(null);const [deletingField,setDeletingField]=useState<ProfileField|null>(null);
  const refresh=()=>{setRevision(v=>v+1);onChanged()};
  useEffect(()=>{const timer=setInterval(()=>setRevision(v=>v+1),5000);return()=>clearInterval(timer)},[space]);
  async function perform(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  useEffect(()=>{let live=true;setLoading(view==='facts'?Object.keys(facts).length===0:profile.length===0);setError('');
    const params=new URLSearchParams({scope_kind:scope.kind,scope_id:scope.id,page:String(page)});
    const timer=setTimeout(async()=>{try{
      const p=await api<{fields:ProfileField[]}>(`/memory/spaces/${space}/profile`);
      if(!live)return;setProfile(p.fields);
      if(view==='facts'){const groups=await Promise.all((category?[category]:Object.keys(categoryLabels)).map(async key=>{const filter=new URLSearchParams({q:query,category:key,status,page:String(categoryPages[key]||1)});return [key,await api<Page<RecordItem>>(`/memory/spaces/${space}/items?${filter}`)] as const}));if(live)setFacts(Object.fromEntries(groups))}
    }catch(e){if(live)setError((e as Error).message)}finally{if(live)setLoading(false)}},150);
    return()=>{live=false;clearTimeout(timer)};
  },[space,scope.id,scope.kind,view,query,category,status,page,categoryPages,revision,refreshKey]);
  useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy){setEditing(null);setDeletingField(null);setNewField(null);setGroupEditor(null);setGroupConfirmation(null)}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[busy]);
  const draft=(record?:RecordItem,key=''):Draft=>({...(record?{id:record.id,version:record.version}:{}),content:record?.content||'',category:record?.category||'fact',memory_type:record?.memory_type||(key?'profile':'fact'),profile_key:record?.profile_key||key,scope_kind:record?.scope_kind||(key?'personal':scope.kind),scope_id:record?.scope_id||(key?'personal':scope.id),conditions:record?.conditions||'',topic_key:record?.topic_key||'',locked:record?Boolean(record.locked):true});
  const details=(record:RecordItem)=><details className="lm-source"><summary>{t('查看来源')}</summary><p>{t(record.source_kind==='legacy'?'旧版记忆，保留原有来源':'最近维护来源')} · {t(record.source_kind==='manual'?'手动维护':record.source_kind==='user_confirmed'?'用户确认':'用户陈述')}</p>{record.source_quote&&<blockquote>{record.source_quote}</blockquote>}{record.source_kind==='manual'&&record.source_quote&&<small>{t('内容已手动修改，以下是原始提取来源。')}</small>}{record.source_thread&&<button className="back-link" onClick={()=>onSource(record.source_thread!)}>{t('打开来源对话')}</button>}</details>;
  const fieldActions=(field:ProfileField)=><div className="memory-card-actions"><button className="secondary" disabled={busy||readOnly} onClick={()=>setEditing(draft(field.memory||undefined,field.key))}><Pencil size={14}/>{t(field.memory?'编辑':'填写')}</button><button className="secondary" disabled={busy||readOnly} aria-label={t('删除档案维度“{0}”',field.custom?field.label:t(field.label))} onClick={()=>setDeletingField(field)}><Trash2 size={14}/>{t('删除')}</button></div>;
  return <section className="lm-workspace">
    <div className="memory-layer-tabs" role="tablist" aria-label={t('记忆分层')}>
      <button role="tab" aria-selected={layer==='semantic'} onClick={()=>{setLayer('semantic');setPage(1);setRuleSeeds([]);setRuleId(undefined)}}><span className="memory-layer-icon"><BrainCircuit size={18}/></span><span><b>{t('语义记忆')}</b><small>{t('我的档案、事实与偏好')}</small></span></button>
      <button role="tab" aria-selected={layer==='episodes'} onClick={()=>{setLayer('episodes');setPage(1);setRuleSeeds([]);setRuleId(undefined)}}><span className="memory-layer-icon"><Clock3 size={18}/></span><span><b>{t('情景记忆')}</b><small>{t('值得保留的任务经历')}</small></span></button>
      <button role="tab" aria-selected={layer==='rules'} onClick={()=>{setLayer('rules');setPage(1);setRuleSeeds([]);setRuleId(undefined)}}><span className="memory-layer-icon"><ListChecks size={18}/></span><span><b>{t('程序记忆')}</b><small>{t('我确认启用的协作规则')}</small></span></button>
    </div>
    {layer==='semantic'&&<div className="memory-view-tabs memory-subtabs" role="tablist" aria-label={t('语义记忆分类')}>{(['profile','facts'] as const).map(v=><button role="tab" key={v} aria-selected={view===v} onClick={()=>{setView(v);setPage(1)}}>{t(v==='profile'?'我的档案':'事实与偏好')}</button>)}</div>}
    {error&&<p className="knowledge-error" role="alert">{t(error)}</p>}
    {layer==='semantic'&&view==='profile'&&<article className="memory-card lm-profile-sheet">
      <header className="lm-sheet-heading"><div><h3><UserRound size={18}/>{t('我的档案')}</h3><p className="field-hint">{t('你的基本信息与长期偏好，可随时补充或修改。')}</p></div><button className="secondary" disabled={busy||readOnly} onClick={()=>{setError('');setNewField({label:'',description:'',content:''})}}><Plus size={15}/>{t('新增维度')}</button></header>
      {loading?<p role="status">{t('正在加载…')}</p>:<div className="lm-profile-rows">{profile.map(field=><div className="lm-profile-row" key={field.key}><div className="lm-field-name"><strong>{field.custom?field.label:t(field.label)}</strong>{field.description&&<small>{field.description}</small>}</div><div className="lm-field-value"><p className={'memory-content '+(!field.memory?'lm-field-empty':'')}>{field.memory?.content||t('尚未设置')}</p>{field.memory&&<><small className="lm-row-state">{t(field.memory.locked?'已锁定':'自动维护')}{field.memory.expired?' · '+t('已过期'):''}</small>{details(field.memory)}</>}</div>{fieldActions(field)}</div>)}</div>}
    </article>}
    {layer==='semantic'&&view==='facts'&&<><div className="lm-fact-toolbar"><div className="memory-search"><Search size={16}/><input className="memory-search-input" aria-label={t('搜索事实记忆')} placeholder={t('搜索事实记忆')} value={query} maxLength={200} onChange={e=>{setQuery(e.target.value);setCategoryPages({})}}/></div><select aria-label={t('记忆类型')} value={category} onChange={e=>{setCategory(e.target.value);setCategoryPages({})}}><option value="">{t('全部类型')}</option>{Object.entries(categoryLabels).map(([key,label])=><option key={key} value={key}>{t(label)}</option>)}</select></div>
      {loading?<p role="status">{t('正在加载…')}</p>:<div className="lm-grouped-facts">{Object.entries(categoryLabels).filter(([key])=>!category||category===key).map(([key,label])=><article className="memory-card lm-fact-group" key={key}><header className="lm-sheet-heading"><h3>{t(label)}</h3><button className="secondary" disabled={busy} onClick={()=>perform(async()=>{const data=await api<{token:string;content:string}>(`/memory/spaces/${space}/categories/${key}`);setGroupConfirmation(null);setGroupEditor({category:key,...data,originalContent:data.content})})}><Pencil size={14}/>{t('管理')}</button></header>{!facts[key]?.items.length?<p className="field-hint">{t('此类型暂无匹配的记忆。')}</p>:<>{facts[key].items.slice(0,3).map(record=><div className="lm-fact-row lm-fact-text" key={record.id}><div className="lm-field-value"><p className="memory-content">{record.content}</p>{record.conditions&&<p className="lm-condition">{t('适用条件')}：{record.conditions}</p>}{record.expired&&<small className="lm-row-state">{t('已过期')}</small>}</div></div>)}{facts[key].total>3&&<p className="lm-preview-note">{t('共 {0} 条，仅显示前 {1} 条。点击“管理”查看全部内容。',facts[key].total,3)}</p>}</>}</article>)}</div>}
    </>}
    {groupEditor&&<div className="modal-backdrop"><section className="modal small-modal lm-group-editor" role="dialog" aria-modal="true" aria-labelledby="group-edit-title"><header><h2 id="group-edit-title">{t(groupConfirmation?'确认删除并保存':'管理')} · {t(categoryLabels[groupEditor.category])}</h2><button aria-label={t('关闭')} disabled={busy} onClick={()=>{setGroupEditor(null);setGroupConfirmation(null)}}><X size={18}/></button></header><form className="memory-edit-form" onSubmit={e=>{e.preventDefault();perform(async()=>{const base=`/memory/spaces/${space}/categories/${groupEditor.category}`;const body={token:groupEditor.token,content:groupEditor.content};if(!groupConfirmation){const preview=await api<{confirmation:string;removed:string[];related:{id:string;kind:string;title:string}[]}>(base+'/preview',{method:'POST',body:JSON.stringify(body)});if(preview.removed.length){setGroupConfirmation(preview);return;}}await api(base,{method:'PUT',body:JSON.stringify({...body,confirmation:groupConfirmation?.confirmation})});setGroupEditor(null);setGroupConfirmation(null);setCategoryPages({})})}}>
      {groupConfirmation?<><p>{t('以下记忆将被删除，不能通过页面恢复。需要找回时须使用备份。原始聊天和已有备份保留。')}</p><ul className="memory-delete-preview">{groupConfirmation.removed.map((content,i)=><li key={i}>{content}</li>)}</ul>{groupConfirmation.related.length>0&&<><p>{t('以下相关记忆也会一并删除：')}</p><ul className="memory-delete-preview">{groupConfirmation.related.map(item=><li key={item.id}>{item.title}</li>)}</ul></>}</>:<><label>{t('此类型的记忆')}<textarea rows={14} maxLength={200000} value={groupEditor.content} onChange={e=>setGroupEditor({...groupEditor,content:e.target.value})}/></label><p className="field-hint">{t('每行一条，可统一添加或修改。包含该类型全部记忆，不受搜索和分页影响。删去内容后，保存前会请你确认删除。')}</p></>}
      {error&&<p role="alert" className="knowledge-error">{t(error)}</p>}<div className="button-row"><button type="button" className="secondary" disabled={busy} onClick={()=>groupConfirmation?setGroupConfirmation(null):setGroupEditor(null)}>{t(groupConfirmation?'返回编辑':'取消')}</button><button className="primary" disabled={busy}>{t(groupConfirmation?'确认删除并保存':'保存全部')}</button></div></form></section></div>}
    {newField&&<div className="modal-backdrop"><section className="modal small-modal" role="dialog" aria-modal="true" aria-labelledby="profile-field-title"><header><h2 id="profile-field-title">{t('新增档案维度')}</h2><button aria-label={t('关闭')} disabled={busy} onClick={()=>setNewField(null)}><X size={18}/></button></header><form className="memory-edit-form" onSubmit={e=>{e.preventDefault();perform(async()=>{await api(`/memory/spaces/${space}/profile/fields`,{method:'POST',body:JSON.stringify(newField)});setNewField(null)})}}><label>{t('维度名称')}<input autoFocus required maxLength={40} value={newField.label} placeholder={t('例如：职业与角色、常用工具')} onChange={e=>setNewField({...newField,label:e.target.value})}/></label><label>{t('维度说明（选填）')}<input maxLength={200} value={newField.description} placeholder={t('说明这个维度记录什么信息')} onChange={e=>setNewField({...newField,description:e.target.value})}/></label><label>{t('内容（选填）')}<textarea rows={3} maxLength={1000} value={newField.content} onChange={e=>setNewField({...newField,content:e.target.value})}/></label><p className="field-hint">{t('手动填写的内容默认锁定；未填写的维度可稍后编辑，或由自动学习补充。')}</p>{error&&<p role="alert" className="knowledge-error">{t(error)}</p>}<div className="button-row"><button type="button" className="secondary" disabled={busy} onClick={()=>setNewField(null)}>{t('取消')}</button><button className="primary" disabled={busy||readOnly||!newField.label.trim()}>{t('保存')}</button></div></form></section></div>}
    {layer==='episodes'&&<Episodes initialId={episodeId} space={space} scope={scope} readOnly={readOnly} onSource={onSource} onProposeRule={id=>{setRuleSeeds([id]);setRuleId(undefined);setLayer('rules')}}/>}
    {layer==='rules'&&<CollaborationRules space={space} scope={scope} readOnly={readOnly} initialId={ruleId} seedEpisodes={ruleSeeds} onChanged={onChanged} onEpisode={id=>{setEpisodeId(id);setLayer('episodes')}}/>}
    {editing&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="lm-edit-title" className="modal small-modal"><header><h2 id="lm-edit-title">{editing.memory_type==='profile'?(profile.find(f=>f.key===editing.profile_key)?.custom?profile.find(f=>f.key===editing.profile_key)!.label:t(fieldLabels[editing.profile_key]||editing.profile_key)):t('编辑事实记忆')}</h2><button aria-label={t('关闭')} disabled={busy||readOnly} onClick={()=>setEditing(null)}><X size={18}/></button></header><form className="memory-edit-form" onSubmit={e=>{e.preventDefault();perform(async()=>{const {id,...body}=editing;await api(id?`/memory/items/${id}`:`/memory/spaces/${space}/items`,{method:id?'PUT':'POST',body:JSON.stringify(body)});setCategoryPages({});setEditing(null)})}}>{editing.memory_type==='fact'&&<label>{t('主题分类')}<select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{Object.entries(categoryLabels).map(([key,label])=><option key={key} value={key}>{t(label)}</option>)}</select></label>}<label>{t('记忆内容')}<textarea required maxLength={1000} rows={4} value={editing.content} onChange={e=>setEditing({...editing,content:e.target.value})}/></label>{editing.memory_type==='fact'&&<label>{t('适用条件')}<input maxLength={500} value={editing.conditions} placeholder={t('例如：仅在工作汇报时')} onChange={e=>setEditing({...editing,conditions:e.target.value})}/></label>}<label className="check-label"><input type="checkbox" checked={editing.locked} onChange={e=>setEditing({...editing,locked:e.target.checked})}/>{t('锁定内容，由我手动维护')}</label>{error&&<p role="alert" className="knowledge-error">{t(error)}</p>}<div className="button-row"><button type="button" className="secondary" disabled={busy||readOnly} onClick={()=>setEditing(null)}>{t('取消')}</button><button className="primary" disabled={busy||!editing.content.trim()}>{t('保存')}</button></div></form></section></div>}
    {deletingField&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="profile-field-delete-title" className="modal small-modal"><header><h2 id="profile-field-delete-title">{t('删除档案维度“{0}”？',deletingField.custom?deletingField.label:t(deletingField.label))}</h2><button aria-label={t('关闭')} disabled={busy} onClick={()=>setDeletingField(null)}><X size={18}/></button></header><p>{t(deletingField.memory?'该维度及其中的记忆内容会被删除，之后不再参与回答。相关记忆会按删除规则一并处理。':'该空白维度会从档案中移除，之后不再自动整理此类信息。')}</p><p className="field-hint">{t('原始聊天和已有备份保留。删除后可以按需要重新新增同名维度。')}</p>{error&&<p role="alert" className="knowledge-error">{t(error)}</p>}<div className="button-row"><button className="secondary" disabled={busy} onClick={()=>setDeletingField(null)}>{t('取消')}</button><button className="primary" disabled={busy||readOnly} onClick={()=>perform(async()=>{await api(`/memory/spaces/${space}/profile/fields/${deletingField.key}`,{method:'DELETE'});setDeletingField(null)})}>{t(busy?'正在删除…':'确认删除维度')}</button></div></section></div>}
  </section>;
}
