import { useEffect,useState } from 'react';
import { api } from './api';
import { t } from './i18n';
type Generation={id:string;state:string;done:number;total:number;dimensions:number;error:string};
type Data={generation:string;embedding:{model:string;dimensions:number}|null;generations:Generation[];usage:{kind:string;calls:number;tokens:number;unknown:number;failed:number}[];queue:Record<string,number>;backups:{id:string;items:number;created:number}[]};
type Preview={backup_id:string;current_items:number;backup_items:number;expected_state:string};
const states:Record<string,string>={building:'构建中',ready:'待切换',active:'当前使用',retired:'已保留',failed:'失败',cancelled:'已取消'};
export function Mem0StoragePanel({readOnly,profiles,onChanged}:{readOnly:boolean;profiles:{id:string;name:string;model:string;kind:string}[];onChanged:()=>void}){
 const [data,setData]=useState<Data|null>(null),[target,setTarget]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[coverage,setCoverage]=useState<{expected:number;present:number;covered:number;missing:number;unexpected:number;wrong_scope:number;complete:boolean}|null>(null);
 const base='/memory/mem0/storage';const load=async()=>setData(await api<Data>(base+'/status'));
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 async function run(fn:()=>Promise<unknown>){setBusy(true);setError('');setNotice('');try{await fn();await load();onChanged()}catch(e){setError(e instanceof Error?e.message:t('操作未完成。'))}finally{setBusy(false)}}
 const disabled=readOnly||busy;
 return <section className="mem0-storage-panel"><h2>{t('存储与诊断')}</h2><p className="field-hint">{t('此页管理整个 Mem0 实例的所有空间。原生正文与历史是正式数据，迁移会先验证新代次再切换。')}</p>{error&&<p role="alert" className="knowledge-error">{error}</p>}{notice&&<p role="status" className="knowledge-notice">{notice}</p>}
 {data&&<><article className="memory-card"><div className="memory-card-top"><b>{t('原生存储覆盖')}</b><button className="secondary" disabled={busy} onClick={()=>run(async()=>setCoverage(await api(base+'/check',{method:'POST'})))}>{t('核对覆盖')}</button></div><p>{t('当前代次')}：{data.generation==='legacy'?t('初始代次'):data.generation.slice(0,8)}</p><p>{data.embedding?.model} {data.embedding&&' · '+data.embedding.dimensions}</p>{coverage&&<p className={coverage.complete?'knowledge-notice':'knowledge-error'}>{t('应有 {0} · 已覆盖 {1} · 缺失 {2} · 未知 {3} · 范围异常 {4}',coverage.expected,coverage.covered,coverage.missing,coverage.unexpected,coverage.wrong_scope)}</p>}</article>
 <article className="memory-card"><h3>{t('嵌入模型迁移')}</h3><p className="field-hint">{t('先在设置中添加目标嵌入模型。迁移保留原生 ID、正文和历史；构建期间若记忆变化，需重新创建代次。')}</p><div className="memory-toolbar"><label>{t('目标嵌入模型')}<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">{t('请选择')}</option>{profiles.filter(p=>p.kind==='embedding').map(p=><option key={p.id} value={p.id}>{p.name} · {p.model}</option>)}</select></label><button className="primary" disabled={disabled||!target} onClick={()=>run(()=>api(base+'/generations',{method:'POST',body:JSON.stringify({embedding_profile_id:target})}))}>{t('创建迁移代次')}</button></div>{data.generations.map(g=><div className="memory-card" key={g.id}><div className="memory-card-top"><b>{g.id.slice(0,8)} · {t(states[g.state]||g.state)}</b><span>{g.done} / {g.total}</span></div>{g.error&&<p>{t('构建未完成或由快照恢复，请核对当前状态。')}</p>}<div className="memory-card-actions">{['building','failed'].includes(g.state)&&<button className="secondary" disabled={disabled} onClick={()=>run(()=>api(base+'/generations/'+g.id+'/continue',{method:'POST'}))}>{t('继续构建（下一批）')}</button>}{g.state==='ready'&&<button className="primary" disabled={disabled} onClick={()=>run(()=>api(base+'/generations/'+g.id+'/publish',{method:'POST'}))}>{t('验证并切换')}</button>}{['building','failed','ready'].includes(g.state)&&<button className="secondary" disabled={disabled} onClick={()=>run(()=>api(base+'/generations/'+g.id+'/cancel',{method:'POST'}))}>{t('取消迁移')}</button>}</div></div>)}</article>
 <article className="memory-card"><div className="memory-card-top"><h3>{t('本机备份与恢复')}</h3><button className="primary" disabled={disabled} onClick={()=>run(()=>api(base+'/backups',{method:'POST'}))}>{t('创建一致性备份')}</button></div><p className="field-hint">{t('备份包括 Mem0 原生存储、历史、形成来源、派生上下文和空间配置，不含完整原始聊天库、其他引擎或模型密钥。下载包可另存；此页从本机已登记快照恢复。')}</p>{data.backups.map(b=><div className="memory-card-actions" key={b.id}><span>{new Date(b.created*1000).toLocaleString()} · {t('共 {0} 条',b.items)}</span><a className="secondary" href={'/api'+base+'/backups/'+b.id+'/download'} download>{t('下载备份')}</a><button className="secondary" disabled={disabled} onClick={()=>run(async()=>setPreview(await api<Preview>(base+'/backups/'+b.id+'/preview',{method:'POST'})))}>{t('预览恢复')}</button></div>)}</article>
 <article className="memory-card"><h3>{t('队列与调用用量')}</h3><p>{Object.entries(data.queue).map(([key,n])=>t(({pending:'等待处理',awaiting_answer:'等待回答完成',running:'正在处理',completed:'已完成',failed:'失败',needs_reconcile:'结果待核对',cancelled:'已取消',reconciled:'已核对',skipped:'已跳过'} as Record<string,string>)[key]||key)+' '+n).join(' · ')||t('暂无摄取任务')}</p><p className="field-hint">{t('Token 仅累计服务商实际报告值；嵌入 SDK 未提供用量的调用标为未知，不按零消耗计算。')}</p><div className="mem0-table-wrap"><table><thead><tr><th>{t('调用类型')}</th><th>{t('次数')}</th><th>Token</th><th>{t('用量未知')}</th><th>{t('失败')}</th></tr></thead><tbody>{data.usage.map(u=><tr key={u.kind}><td>{t(({native_llm:'长期记忆推理',native_embedding:'原生嵌入',context_summary:'会话摘要',context_task:'任务整理',migration_embedding:'迁移嵌入'} as Record<string,string>)[u.kind]||u.kind)}</td><td>{u.calls}</td><td>{u.tokens}</td><td>{u.unknown}</td><td>{u.failed}</td></tr>)}</tbody></table></div></article>
 </>}
 {preview&&<div className="modal-backdrop"><section className="modal small-modal" role="dialog" aria-modal="true" aria-labelledby="mem0-restore-title"><h2 id="mem0-restore-title">{t('确认恢复 Mem0 快照？')}</h2><p>{t('当前 {0} 条，备份 {1} 条。恢复会替换当前原生内容，可能撤销备份之后的新增和编辑。',preview.current_items,preview.backup_items)}</p><p>{t('会先保存当前实例安全快照，并保留最新删除屏障。旧摘要、任务记录和现有会话前缀将失效，避免已删除内容复活。')}</p>{error&&<p role="alert">{error}</p>}<div className="button-row"><button className="secondary" disabled={busy} onClick={()=>setPreview(null)}>{t('取消')}</button><button className="primary" disabled={disabled} onClick={()=>run(async()=>{await api(base+'/backups/'+preview.backup_id+'/restore',{method:'POST',body:JSON.stringify({expected_state:preview.expected_state})});setPreview(null);setCoverage(null);setNotice(t('快照已恢复，建议新建对话继续。'))})}>{t('确认恢复')}</button></div></section></div>}
 </section>
}
