import { useEffect,useState } from 'react';
import { api } from './api';
import { t } from './i18n';
type Fields={goal:string;constraints:string[];decisions:string[];pending:string[]};
type Context={thread_id:string;version:number;summary:{text?:string;source_ids?:string[];model?:string};task:{fields?:Fields;locked?:boolean;status?:string;origin?:string};sources:{id:string;run_id:string;created:number}[];budget:{policy?:string;estimated_input?:number;window?:number;excluded_messages?:number;summary_messages?:number};exclusions:{turn_id:string}[];revoked_before:number|null;error:string};
export function Mem0ContextPanel({space,readOnly,onSource}:{space:string;readOnly:boolean;onSource:(id:string)=>void}){
 const [threads,setThreads]=useState<{thread_id:string;version:number;updated:number}[]>([]),[total,setTotal]=useState(0),[thread,setThread]=useState(''),[data,setData]=useState<Context|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState<(Fields&{locked:boolean;status:string;version:number})|null>(null);
 const base='/memory/mem0/'+space+'/contexts';
 const load=async()=>{setData(await api<Context>(base+'/'+thread))};
 useEffect(()=>{let cancel=false;api<{items:typeof threads;total:number}>(base).then(r=>{if(!cancel){setTotal(r.total);setThreads(r.items);if(r.items.length)setThread(r.items[0].thread_id)}}).catch(e=>setError(e.message));return()=>{cancel=true}},[base]);
 useEffect(()=>{let cancel=false;if(thread)api<Context>(base+'/'+thread).then(r=>{if(!cancel)setData(r)}).catch(e=>setError(e.message));return()=>{cancel=true}},[base,thread]);
 async function run(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:t('操作未完成。'))}finally{setBusy(false)}}
 return <section className="mem0-context-panel"><h2>{t('会话上下文')}</h2><p className="field-hint">{t('工作台扩展：摘要与任务记录仅用于对话衔接，不会自动写入长期事实。策略在记忆引擎中设置。')}</p>{error&&<p role="alert" className="knowledge-error">{error}</p>}
 {!threads.length?<p className="memory-empty">{t('还没有 Mem0 会话上下文。切换到 Mem0 并完成一次新提问后显示。')}</p>:<><div className="memory-toolbar"><label>{t('选择会话')}<select value={thread} onChange={e=>{setThread(e.target.value);setEdit(null);setData(null)}}>{threads.map(v=><option key={v.thread_id} value={v.thread_id}>{v.thread_id} · {new Date(v.updated*1000).toLocaleString()}</option>)}</select></label>{threads.length<total&&<button className="secondary" disabled={busy} onClick={()=>run(async()=>{const r=await api<{items:typeof threads;total:number}>(base+'?offset='+threads.length);setThreads([...threads,...r.items]);setTotal(r.total)})}>{t('加载更多会话')}</button>}<button className="secondary" onClick={()=>onSource(thread)}>{t('打开来源对话')}</button><button className="secondary" disabled={busy} onClick={()=>run(load)}>{t('刷新')}</button></div>
 {data&&<><div className="memory-status"><span>{t(data.budget.policy==='mem0_summary'?'摘要衔接模式':'近期窗口模式')} · v{data.version}</span><span>{t('估算输入 {0} / 窗口 {1}',data.budget.estimated_input||0,data.budget.window||0)}</span></div>{data.error&&<p className="knowledge-notice">{t(data.error==='task_update_failed'?'任务自动整理未完成，保留已有记录，可手动编辑。':'来源或存储已改变，旧摘要与任务记录已失效。')}</p>}
 <article className="memory-card"><div className="memory-card-top"><b>{t('会话摘要')}</b><button className="secondary" disabled={busy||readOnly} onClick={()=>run(()=>api(base+'/'+thread+'/rebuild',{method:'POST',body:JSON.stringify({version:data.version})}))}>{t('重建摘要')}</button></div><p className="memory-content">{data.summary.text||t('尚未生成摘要；近期原文仍按预算使用。')}</p><small>{t('摘要覆盖 {0} 条来源消息',data.summary.source_ids?.length||0)} {data.summary.model}</small></article>
 <article className="memory-card"><div className="memory-card-top"><b>{t('Mem0 任务记录')}</b><button className="secondary" disabled={busy||readOnly} onClick={()=>setEdit({...data.task.fields||{goal:'',constraints:[],decisions:[],pending:[]},version:data.version,locked:data.task.locked!==false,status:data.task.status||'active'})}>{t('编辑')}</button></div>
 {edit?<form className="memory-edit-form" onSubmit={e=>{e.preventDefault();run(async()=>{await api(base+'/'+thread+'/task',{method:'PUT',body:JSON.stringify(edit)});setEdit(null)})}}><label>{t('目标')}<textarea maxLength={500} value={edit.goal} onChange={e=>setEdit({...edit,goal:e.target.value})}/></label>{(['constraints','decisions','pending'] as const).map(key=><label key={key}>{t({constraints:'约束（每行一条）',decisions:'决定（每行一条）',pending:'待办（每行一条）'}[key])}<textarea rows={3} value={edit[key].join('\n')} onChange={e=>setEdit({...edit,[key]:e.target.value.split('\n')})}/></label>)}<label>{t('任务状态')}<select value={edit.status} onChange={e=>setEdit({...edit,status:e.target.value})}><option value="active">{t('进行中')}</option><option value="paused">{t('暂停')}</option><option value="completed">{t('已完成')}</option></select></label><label className="check-label"><input type="checkbox" checked={edit.locked} onChange={e=>setEdit({...edit,locked:e.target.checked})}/>{t('锁定任务记录，停止自动覆盖')}</label><div className="button-row"><button type="button" className="secondary" onClick={()=>setEdit(null)}>{t('取消')}</button><button className="primary" disabled={busy||readOnly}>{t('保存')}</button></div></form>:<><p>{data.task.fields?.goal||t('暂无任务目标')}</p>{(['constraints','decisions','pending'] as const).map(k=><div key={k}><b>{t({constraints:'约束',decisions:'决定',pending:'待办'}[k])}</b><ul>{data.task.fields?.[k].map((v,i)=><li key={i}>{v}</li>)}</ul></div>)}<small>{t(data.task.locked?'已锁定':'自动维护')}</small></>}</article>
 <details className="memory-card"><summary>{t('来源范围与排除')}</summary><p className="field-hint">{t('排除一轮会清空派生摘要与任务，并暂时停用该会话现有原文前缀，避免后续回答带回旧内容。新提问仍可使用；原聊天不删除，长期事实需另行管理。')}</p>{data.revoked_before&&<p>{t('部分原文因相关记忆停用或恢复快照而失效，不能直接恢复。')}</p>}{data.sources.map((s,i)=>{const excluded=data.exclusions.some(e=>e.turn_id===s.id);return <div className="memory-card-actions" key={s.id}><span>{t('第 {0} 轮',i+1)} · {s.created?new Date(s.created*1000).toLocaleString():s.id.slice(0,8)}</span><button className="secondary" disabled={busy||readOnly} onClick={()=>run(()=>api(base+'/'+thread+'/source',{method:'PUT',body:JSON.stringify({version:data.version,turn_id:s.id,excluded:!excluded})}))}>{t(excluded?'恢复来源':'排除来源')}</button></div>})}</details>
 </>}
 </>}
 </section>
}
