import {useEffect,useState} from 'react';
import {Pencil,Plus,Search,Trash2,X} from 'lucide-react';
import {api} from './api';
import {t} from './i18n';
type EventRow={id?:string;version?:number;title:string;description:string;topic:string;occurred:string;ended:string;outcome:string;result:string;lesson:string;locked:boolean};
type Data={items:EventRow[];topics:string[];more:boolean;pending:{id:string;state:string}[]};
const empty:EventRow={title:'',description:'',topic:'',occurred:'',ended:'',outcome:'unknown',result:'',lesson:'',locked:true};
const outcomes:Record<string,string>={unknown:'结果未明确',ongoing:'进行中',completed:'已完成',failed:'未成功'};
export function Mem0Events({space,readOnly,refreshKey,onChanged}:{space:string;readOnly:boolean;refreshKey:unknown;onChanged:()=>void}){
 const base='/memory/mem0/'+space;
 const [data,setData]=useState<Data|null>(null),[q,setQ]=useState(''),[topic,setTopic]=useState(''),[page,setPage]=useState(1),[tick,setTick]=useState(0);
 const [editor,setEditor]=useState<EventRow|null>(null),[deleting,setDeleting]=useState<EventRow|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loadError,setLoadError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let cancelled=false;api<Data>(`${base}/events?q=${encodeURIComponent(q)}&topic=${encodeURIComponent(topic)}&page=${page}`).then(v=>{if(!cancelled){setData(v);setLoadError('')}}).catch(e=>{if(!cancelled)setLoadError(e.message)});const timer=setTimeout(()=>setTick(x=>x+1),5000);return()=>{cancelled=true;clearTimeout(timer)}},[base,q,topic,page,tick,refreshKey]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();setTick(v=>v+1);onChanged()}catch(e){setError(e instanceof Error?e.message:t('操作未完成。'))}finally{setBusy(false)}}
 function change(key:keyof EventRow,value:string|boolean){if(editor)setEditor({...editor,[key]:value})}
 function result(status:string){setNotice(t(status==='completed'?'记忆已保存。':'事件保存尚未完成，请检查配置后核对保存结果。'));setEditor(null);setDeleting(null)}
 return <section className="mem0-events">
  <p className="field-hint">{t('保留学习进展与工作经历。历史结果仅作参考，不代表当前状态。')}</p>
  <div className="memory-toolbar lm-fact-toolbar"><div className="memory-search"><Search size={16}/><input className="memory-search-input" aria-label={t('搜索事件')} placeholder={t('搜索事件')} maxLength={200} value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/>{q&&<button aria-label={t('清空搜索')} onClick={()=>setQ('')}><X size={14}/></button>}</div><select aria-label={t('事件主题')} value={topic} onChange={e=>{setTopic(e.target.value);setPage(1)}}><option value="">{t('全部主题')}</option>{data?.topics.map(v=><option key={v}>{v}</option>)}</select><button className="secondary" disabled={readOnly||busy} onClick={()=>{setError('');setEditor({...empty})}}><Plus size={15}/>{t('添加经历')}</button></div>
  {(error||loadError)&&<p role="alert" className="knowledge-error">{error||loadError}</p>}{notice&&<p role="status" className="knowledge-notice">{notice}</p>}
  {data?.pending.map(op=><div className="knowledge-notice" key={op.id}><p>{t(op.state==='failed'?'有一条事件未能整理。现有记忆保留，可忽略此次失败。':'事件保存尚未完成，请检查配置后核对保存结果。')}</p><button className="secondary" disabled={readOnly||busy} onClick={()=>run(async()=>{await api(base+'/event-operations/'+op.id+'/resolve',{method:'POST'})})}>{t(op.state==='failed'?'忽略此次失败':'核对保存结果')}</button></div>)}
  {!data&&!loadError&&<p role="status">{t('正在加载…')}</p>}
  {data&&!data.items.length&&!data.pending.length&&<div className="memory-card memory-empty-note"><p>{t('暂无匹配的经历。新的对话中出现值得保留的学习进展或工作结果后，会在这里整理。')}</p></div>}
  <div className="mem0-event-list">{data?.items.map(item=><article className="mem0-event-row" key={item.id}>
   <div className="mem0-event-time">{item.occurred||t('时间未知')}{item.ended&&<> — {item.ended}</>}</div>
   <div className="mem0-event-body"><header><h3>{item.title}</h3><span className="field-hint">{item.topic}</span></header><p className="memory-content">{item.description}</p><div className="mem0-event-labels"><span>{t(outcomes[item.outcome])}</span></div>{item.result&&<p><strong>{t('结果')}：</strong>{item.result}</p>}{item.lesson&&<p><strong>{t('经验')}：</strong>{item.lesson}</p>}</div>
   <div className="button-row"><button className="secondary" aria-label={t('编辑经历')+' · '+item.title} disabled={readOnly||busy} onClick={()=>{setError('');setEditor({...item,locked:true})}}><Pencil size={15}/></button><button className="secondary" aria-label={t('删除经历')+' · '+item.title} disabled={readOnly||busy} onClick={()=>{setError('');setDeleting(item)}}><Trash2 size={15}/></button></div>
  </article>)}</div>
  {(page>1||data?.more)&&<div className="button-row"><button className="secondary" disabled={page<=1} onClick={()=>setPage(v=>v-1)}>{t('上一页')}</button><button className="secondary" disabled={!data?.more} onClick={()=>setPage(v=>v+1)}>{t('下一页')}</button></div>}
  {editor&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="mem0-event-title" className="modal small-modal lm-group-editor"><header><h2 id="mem0-event-title">{t(editor.id?'编辑经历':'添加经历')}</h2><button aria-label={t('关闭')} disabled={busy} onClick={()=>setEditor(null)}><X size={18}/></button></header><form className="memory-edit-form" onSubmit={e=>{e.preventDefault();run(async()=>{const {id,...body}=editor;const payload=Object.fromEntries(Object.entries(body).filter(([key])=>['title','description','topic','occurred','ended','outcome','result','lesson','locked','version'].includes(key)));const res=await api<{status:string}>(base+'/events'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(payload)});result(res.status)})}}>
   <label>{t('标题')}<input required maxLength={120} value={editor.title} onChange={e=>change('title',e.target.value)}/></label><label>{t('事件主题')}<input maxLength={80} value={editor.topic} onChange={e=>change('topic',e.target.value)}/></label>
   <div className="mem0-event-dates"><label>{t('发生时间')}<input placeholder="YYYY / YYYY-MM / YYYY-MM-DD" maxLength={10} value={editor.occurred} onChange={e=>change('occurred',e.target.value)}/></label><label>{t('结束时间（可选）')}<input maxLength={10} value={editor.ended} onChange={e=>change('ended',e.target.value)}/></label></div><p className="field-hint">{t('不确定的时间请留空；不会用记录日期代替发生日期。')}</p>
   <label>{t('经过')}<textarea required rows={3} maxLength={1400} value={editor.description} onChange={e=>change('description',e.target.value)}/></label><label>{t('结果状态')}<select value={editor.outcome} onChange={e=>change('outcome',e.target.value)}>{Object.entries(outcomes).map(([key,label])=><option key={key} value={key}>{t(label)}</option>)}</select></label><label>{t('结果')}<textarea rows={2} maxLength={800} value={editor.result} onChange={e=>change('result',e.target.value)}/></label><label>{t('经验')}<textarea rows={2} maxLength={800} value={editor.lesson} onChange={e=>change('lesson',e.target.value)}/></label><label className="checkbox-label"><input type="checkbox" checked={editor.locked} onChange={e=>change('locked',e.target.checked)}/>{t('锁定内容，防止自动整理覆盖')}</label>
   {error&&<p role="alert" className="knowledge-error">{error}</p>}<div className="button-row"><button type="button" className="secondary" disabled={busy} onClick={()=>setEditor(null)}>{t('取消')}</button><button className="primary" disabled={busy||readOnly}>{t(busy?'正在保存…':'保存')}</button></div>
  </form></section></div>}
  {deleting&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="mem0-event-delete" className="modal small-modal"><header><h2 id="mem0-event-delete">{t('删除经历')}</h2></header><p>{deleting.title}</p><p>{t('删除后不再用于回答，相关会话摘要将失效。原始聊天和已有备份保留。')}</p>{error&&<p role="alert" className="knowledge-error">{error}</p>}<div className="button-row"><button className="secondary" disabled={busy} onClick={()=>setDeleting(null)}>{t('取消')}</button><button className="primary" disabled={busy||readOnly} onClick={()=>run(async()=>{const r=await api<{status:string}>(base+'/events/'+deleting.id,{method:'DELETE',body:JSON.stringify({version:deleting.version})});result(r.status)})}>{t('确认删除')}</button></div></section></div>}
 </section>
}
