import { useEffect, useState } from 'react';
import { Download, RefreshCw, Trash2 } from 'lucide-react';
import { api } from './api';
import { t } from './i18n';

type Item = {id:string;kind:string;title:string;version:number;status:string;expires:number|null;expired:boolean;archive_suggested:boolean};
type Impact = {token:string;items:Item[];runs:{thread_id:string;run_id:string}[];counts:Record<string,number>;relations:{source:string;target:string}[]};
type Data = {items:Item[];total:number;page:number;pending_reviews:number;contexts:{thread_id:string;run_id:string;needs_rebuild:boolean;manifest:{summary_version:number;task_version:number;summary_sources:string[];task_sources:string[];excluded_turns:string[];usage:{calls?:number;tokens?:number;unknown?:boolean}}}[];indices:{signature:string;state:string;total:number;covered:number;error:string;updated:number}[];usage:{kind:string;calls:number;tokens:number;unknown:number;failed:number}[];jobs:Record<string,Record<string,number>>;audit:{id:number;kind:string;action:string;object_id:string;counts:Record<string,number>;created:number}[]};
const kinds:Record<string,string>={profile:'我的档案',fact:'事实记忆',episode:'任务经历',rule:'协作规则',semantic:'档案与事实',rule_generation:'规则生成',rule_evaluation:'规则评估',rule_judge:'规则评审'};
const states:Record<string,string>={active:'生效中',archived:'已归档',candidate:'候选',blocked:'已停用',expired:'已过期',pending:'待处理',running:'正在处理',failed:'失败',completed:'已完成',cancelled:'已取消',skipped:'已跳过',retry_wait:'等待重试',collecting:'收集事件中',awaiting_answer:'等待回答完成',ready:'完整可用',building:'构建中',stale:'待更新',deleted:'已删除'};

export function MemoryDeleteDialog({space,id,onClose,onDeleted}:{space:string;id:string;onClose:()=>void;onDeleted:()=>void}) {
  const [impact,setImpact]=useState<Impact|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{let live=true;api<Impact>(`/memory/spaces/${space}/objects/${id}/impact`).then(r=>{if(live)setImpact(r)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[space,id]);
  return <div className="modal-backdrop"><section className="modal small-modal" role="dialog" aria-modal="true" aria-labelledby="lifecycle-delete-title"><h2 id="lifecycle-delete-title">{t('删除记忆？')}</h2><p>{t('删除后将停止使用以下记忆，包括由它形成的相关记忆。原始聊天和已有备份保留。')}</p>{!impact&&!error&&<p role="status">{t('正在加载…')}</p>}{impact&&<div className="lifecycle-impact-list">{impact.items.map(r=><p key={r.id}><span className="memory-badge">{t(kinds[r.kind])}</span> {r.title}</p>)}</div>}{error&&<p className="knowledge-error" role="alert">{t(error)}</p>}<div className="button-row"><button className="secondary" disabled={busy} onClick={onClose}>{t('取消')}</button><button className="primary" disabled={busy||!impact} onClick={async()=>{if(!impact)return;setBusy(true);setError('');try{await api(`/memory/spaces/${space}/objects/${id}`,{method:'DELETE',body:JSON.stringify({token:impact.token})});onDeleted()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{t('确认删除')}</button></div></section></div>;

}

export function MemoryLifecycle({space,readOnly,onChanged,onSource,contextsOnly=false}:{space:string;readOnly:boolean;onChanged:()=>void;onSource:(id:string)=>void;contextsOnly?:boolean}) {
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[page,setPage]=useState(1),[kind,setKind]=useState('all');
  const [deleting,setDeleting]=useState<string>(),[editing,setEditing]=useState<Item>(),[expires,setExpires]=useState('');
  const refresh=()=>{setRevision(r=>r+1);onChanged()};
  useEffect(()=>{let live=true;setError('');api<Data>(`/memory/spaces/${space}/lifecycle?page=${page}&kind=${kind}`).then(r=>{if(live)setData(r)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[space,page,kind,revision]);
  async function perform(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="memory-insights lifecycle-panel"><div className="memory-card-top"><h2>{t(contextsOnly?'任务上下文':'生命周期与诊断')}</h2><button className="secondary" disabled={busy} onClick={refresh}><RefreshCw size={15}/>{t('刷新')}</button></div><p className="field-hint">{t('按来源追踪四层记忆。记录已准备给模型的内容，不代表模型实际依赖；未记录的历史关系不会被推断为已知。')}</p>{error&&<p className="knowledge-error" role="alert">{t(error)}</p>}{!data?<p role="status">{t('正在加载…')}</p>:contextsOnly?<><p className="field-hint">{t('这里显示近期会话的摘要、任务状态和来源数量，不复制聊天正文。打开对话可编辑任务、排除来源或重建摘要。')}</p>{!data.contexts.length&&<p className="knowledge-notice">{t('下一次使用 LangMem 对话后，会在这里显示任务上下文。')}</p>}{data.contexts.map(c=><article className="memory-card" key={c.thread_id}><div className="memory-card-top"><strong>{t('对话')} · {c.thread_id}</strong><span className="memory-badge">{t(c.needs_rebuild?'来源已失效，等待重建':'来源检查通过')}</span></div><p>{t('摘要 v{0} · {1} 条来源；任务 v{2} · {3} 条来源',c.manifest.summary_version,c.manifest.summary_sources.length,c.manifest.task_version,c.manifest.task_sources.length)}</p><p className="field-hint">{t('已排除 {0} 个对话轮次',c.manifest.excluded_turns.length)}</p><p className="field-hint">{t('本次上下文整理：{0} 次调用，已报告 {1} Token',c.manifest.usage.calls||0,c.manifest.usage.tokens||0)}{c.manifest.usage.unknown&&' · '+t('部分用量未知')}</p><button className="back-link" onClick={()=>onSource(c.thread_id)}>{t('打开对话管理上下文')}</button></article>)}<div className="button-row"><button className="secondary" disabled={page===1} onClick={()=>setPage(page-1)}>{t('上一页')}</button><span>{page}</span><button className="secondary" disabled={data.contexts.length<30} onClick={()=>setPage(page+1)}>{t('下一页')}</button></div></>:<>
    <div className="lifecycle-summary"><article className="memory-card"><h3>{t('保留策略')}</h3><p>{t('默认长期保留，不自动删除。可为单条记忆设置期限；到期即停止直接召回，延长期限可恢复。超过 180 天未维护只建议人工归档，不按低使用次数删除。')}</p></article><article className="memory-card"><h3>{t('备份与恢复')}</h3><p>{t('导出当前 LangMem 实例的全部空间，含记忆、版本、来源和删除屏障；不含聊天、模型密钥、输出文件或 Mem0 数据。备份含个人资料，请自行妥善保管。')}</p><a className="secondary" href="/api/memory/langmem/export" download><Download size={15}/>{t('导出 LangMem 备份')}</a><p className="field-hint">{t('恢复工具会校验备份并恢复到新的隔离目录，不覆盖运行中的工作台。详见 P5 生命周期说明。')}</p></article></div>
    <div className="lm-fact-toolbar"><label>{t('对象类型')}<select value={kind} onChange={e=>{setKind(e.target.value);setPage(1)}}><option value="all">{t('全部')}</option>{['profile','fact','episode','rule'].map(k=><option key={k} value={k}>{t(kinds[k])}</option>)}</select></label><span className="field-hint">{t('共 {0} 项',data.total)} · {t('待处理建议')} {data.pending_reviews}</span></div>
    <div className="lifecycle-objects">{data.items.map(r=><article className="memory-card" key={r.id}><div className="memory-card-top"><span className="memory-badge">{t(kinds[r.kind])}</span><span>{t(r.expired?'已过期':states[r.status]||r.status)} · v{r.version}</span></div><p className="memory-content">{r.title}</p><p className="field-hint">{r.expires?t('保留至 {0}',new Date(r.expires*1000).toLocaleString()):t('长期保留')}{r.archive_suggested&&' · '+t('建议检查是否归档')}</p><div className="memory-card-actions"><button className="secondary" disabled={readOnly||busy} onClick={()=>{setEditing(r);setExpires(r.expires?new Date(r.expires*1000-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):'')}}>{t('设置期限')}</button><button className="secondary" disabled={readOnly||busy} onClick={()=>setDeleting(r.id)}><Trash2 size={14}/>{t('删除')}</button></div></article>)}</div><div className="button-row"><button className="secondary" disabled={page===1} onClick={()=>setPage(page-1)}>{t('上一页')}</button><span>{page} / {Math.max(1,Math.ceil(data.total/30))}</span><button className="secondary" disabled={page*30>=data.total} onClick={()=>setPage(page+1)}>{t('下一页')}</button></div>
    <article className="memory-card"><h3>{t('向量索引覆盖')}</h3><p className="field-hint">{t('关键词检索覆盖全部有效事实。向量索引按嵌入配置分代，每次最多补齐 64 条并持久保存进度；未覆盖全空间时不会使用部分索引或旧模型的索引。')}</p>{!data.indices.length&&<p>{t('尚未构建向量索引')}</p>}{data.indices.map(g=><p key={g.signature}><code>{g.signature.slice(0,10)}</code> · {t(states[g.state]||g.state)} · {g.covered}/{g.total} · {new Date(g.updated*1000).toLocaleString()}{g.error&&' · '+t('构建未完成，可检查配置后继续')}</p>)}<button className="secondary" disabled={readOnly||busy} onClick={()=>perform(()=>api(`/memory/spaces/${space}/index/continue`,{method:'POST'}))}>{t(busy?'正在处理…':'继续构建当前模型索引')}</button></article>
    <article className="memory-card"><h3>{t('后台与用量')}</h3><p className="field-hint">{t('仅统计升级后供应商报告的 Token；未知用量不会当作零费用。后台用量按 LangMem 实例汇总，队列按当前空间统计。数据存储在本地，模型计算是否联网取决于所选模型。')}</p><div className="lifecycle-table"><table><thead><tr><th>{t('对象类型')}</th><th>{t('调用次数')}</th><th>Token</th><th>{t('用量未知')}</th><th>{t('失败')}</th></tr></thead><tbody>{data.usage.map(u=><tr key={u.kind}><td>{t(kinds[u.kind]||u.kind)}</td><td>{u.calls}</td><td>{u.tokens}</td><td>{u.unknown}</td><td>{u.failed}</td></tr>)}</tbody></table></div>{Object.entries(data.jobs).map(([k,counts])=><p key={k}>{t(kinds[k]||k)} · {Object.entries(counts).map(([state,n])=>`${t(states[state]||state)} ${n}`).join(' / ')||t('暂无任务')}</p>)}</article>
    <details className="memory-card"><summary>{t('生命周期操作记录')}</summary>{data.audit.map(a=><p key={a.id}>{new Date(a.created*1000).toLocaleString()} · {t(a.action==='delete'?'删除':'设置期限')} · <code>{a.object_id}</code></p>)}</details>
  </>}{deleting&&<MemoryDeleteDialog space={space} id={deleting} onClose={()=>setDeleting(undefined)} onDeleted={()=>{setDeleting(undefined);refresh()}}/>}{editing&&<div className="modal-backdrop"><section className="modal small-modal" role="dialog" aria-modal="true" aria-labelledby="retention-title"><h2 id="retention-title">{t('设置记忆期限')}</h2><p>{editing.title}</p><label>{t('到期时间（留空则长期保留）')}<input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/></label><p className="field-hint">{t('到期不会清除正文，也不会撤回此前回答。彻底停止已追踪派生内容请使用删除并查看影响预览。')}</p>{error&&<p role="alert">{t(error)}</p>}<div className="button-row"><button className="secondary" disabled={busy} onClick={()=>setEditing(undefined)}>{t('取消')}</button><button className="primary" disabled={busy} onClick={()=>perform(async()=>{await api(`/memory/spaces/${space}/objects/${editing.id}/retention`,{method:'PUT',body:JSON.stringify({version:editing.version,expires_at:expires?new Date(expires).toISOString():null})});setEditing(undefined)})}>{t('保存')}</button></div></section></div>}</section>;
}
