import { useEffect, useState } from 'react';
import { ArrowLeft, Brain, Check, Trash2 } from 'lucide-react';
import { api } from './api';
import { t } from './i18n';
import type { Preferences } from './SettingsPage';
import './memory.css';
import { MemorySwitchDialog } from './MemorySwitchDialog';
import {useMem0Procedures} from './useMem0Procedures';
import { Mem0Workspace } from './Mem0Workspace';
import langmemLogo from './assets/engine-logos/langmem.png';
import mem0Logo from './assets/engine-logos/mem0.svg';
import { LangMemWorkspace } from './LangMemWorkspace';

type EngineId = 'langmem' | 'mem0';
export type MemoryConfig = { langmem:{episodes:boolean;hot_path:boolean;debounce_seconds:number;retrieval:'keyword'|'semantic';embedding_profile_id:string|null;similarity_threshold:number}; mem0: {procedures?:boolean;events?:boolean;context_strategy?:'recent'|'summary';model_profile_id:string|null;embedding_profile_id:string|null;similarity_threshold:number}; engine: EngineId; enabled:boolean; use_memories: boolean; learn_memories: boolean; model_profile_id: string | null; recall_limit: number; context_chars: number; revision?: number };
export type MemorySelection = { enabled?: boolean; write_memories?:boolean; space_id: string; use_memories: boolean; learn_memories: boolean; scope_kind?: 'personal'|'project'|'partner'; scope_id?: string };
export type MemoryOverview = { active_profile_id:string; default_profile_id:string; epoch:number; configs:Record<EngineId, MemoryConfig>; profiles:{id:string;engine:EngineId;active:boolean;implementation:string;capabilities:string[]}[]; current_space_id:string; engine_spaces:Record<EngineId,string>; config: MemoryConfig; spaces: { id: string; name: string; count: number; engine: string; memory_profile_id:string; is_default:boolean; is_current:boolean; deleting?:boolean }[]; engines: { id:EngineId; name: string; version: string }[] };
const configInput = ({ revision: _revision, ...config }: MemoryConfig) => config;
export const defaultMemorySelection = (): MemorySelection => ({ space_id: 'personal', use_memories: true, learn_memories: true });

export function MemoryCenter({ onClose, onChanged, onSource, preferences, chatRunning }: { chatRunning: boolean; onClose: () => void; onChanged: () => void; onSource: (id: string) => void; preferences: Preferences | null }) {
  const proceduresReady=useMem0Procedures();
  const [data, setData] = useState<MemoryOverview | null>(null);
  const [config, setConfig] = useState<MemoryConfig | null>(null);
  const [tab, setTab] = useState<'memories' | 'engine'>('memories');
  const [space, setSpace] = useState('');
  const [engineTab,setEngineTab] = useState<EngineId>('langmem');
  const [reuseSpace,setReuseSpace]=useState('');
  const [switching,setSwitching]=useState<{engine:EngineId;spaceId:string;name:string;freshId:string}|null>(null);
  const [deleting,setDeleting]=useState<MemoryOverview['spaces'][number]|null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const report = (e: unknown) => setError(e instanceof Error ? e.message : t('操作未完成。'));
  async function overview(resetConfig = false) { const result = await api<MemoryOverview>('/memory'); setData(result); setSpace(old=>result.spaces.some(s=>s.id===old)?old:result.current_space_id);setReuseSpace(old=>result.spaces.some(s=>s.id===old&&s.engine===engineTab)?old:result.engine_spaces[engineTab]); if (resetConfig) setConfig(result.configs[engineTab]); onChanged(); }
  async function run(fn: () => Promise<void>) { setBusy(true); setError(''); setNotice(''); try { await fn(); } catch (e) { report(e); } finally { setBusy(false); } }
  useEffect(() => { overview(true).catch(report); }, []);
  useEffect(() => { if (!chatRunning) overview().catch(report); }, [chatRunning]);
  async function activate(engine:EngineId,sid:string,freshName?:string){
    await api('/memory/activate',{method:'POST',body:JSON.stringify({profile_id:engine+'-default',...(freshName?{new_space:{id:switching!.freshId,name:freshName}}:{space_id:sid})})});
    await overview();const selectedSpace=freshName?switching!.freshId:sid;setSpace(selectedSpace);setReuseSpace(selectedSpace);setSwitching(null);setNotice(t('记忆方案已更新，后续对话自动使用当前设置。'));
  }
  const readOnly = data?.spaces.find(s=>s.id===space)?.memory_profile_id !== data?.active_profile_id;
  const currentEngine = data?.spaces.find(s=>s.id===space)?.engine==='mem0'?'mem0':'langmem';
  const activeEngine:EngineId=data?.active_profile_id.startsWith('mem0')?'mem0':'langmem';
  const activeSpace=data?.spaces.find(s=>s.id===data.current_space_id);
  return <main className="knowledge-center memory-center"><header className="knowledge-header"><div><button className="back-link" onClick={onClose}><ArrowLeft size={16}/>{t('回到对话')}</button><span className="eyebrow">PERSONAL MEMORY</span><h1>{t('记忆中心')}</h1><p>{t('留下偏好、目标与经验，让每次对话接得上。')}</p></div>{data?<div className="memory-active-engine"><img src={activeEngine==='mem0'?mem0Logo:langmemLogo} alt=""/><span><b>{activeEngine==='mem0'?'Mem0 OSS':'LangMem'} · {t('正在运行')}</b><small>{activeSpace?.name||t('默认空间')} · {t('后台自动使用')}</small></span></div>:<Brain size={38} strokeWidth={1.3}/>}</header>
    <div className="knowledge-tabs" role="tablist" aria-label={t('记忆中心')}>{(['memories', 'engine'] as const).map(v => <button key={v} role="tab" aria-selected={tab === v} onClick={() => { setTab(v); setError(''); setNotice(''); }}>{t(v === 'memories' ? '我的记忆' : '记忆引擎')}</button>)}</div>
    {error && <div role="alert" className="knowledge-error">{error}</div>}{notice && <div role="status" className="knowledge-notice">{notice}</div>}
    {!data || !config ? <p>{t('正在加载…')}</p> : tab === 'engine' ? <section className="memory-engine">
      <span className="eyebrow">{t('本地记忆方案')}</span><p className="field-hint">{t('在这里统一管理启用状态、当前引擎和记忆空间。记忆在后台工作，适用于所有普通助手和单个伙伴对话。')}</p>
      <div className="memory-engine-options">{data.engines.map(engine => <button type="button" key={engine.id} disabled={busy} aria-pressed={engineTab === engine.id} className={'memory-engine-card ' + (engineTab === engine.id ? 'selected' : '')} onClick={() => {setEngineTab(engine.id);setReuseSpace(data.engine_spaces[engine.id]);setConfig(data.configs[engine.id]);setNotice('');setError('');}}>
        <div className="memory-engine-icon"><img src={engine.id === 'mem0' ? mem0Logo : langmemLogo} alt="" width={32} height={32}/></div><div><h2>{engine.name} <small>v{engine.version}</small></h2><p>{t(engine.id==='mem0'?'原生记忆与历史 · 独立存储 · 本地运行':'结构化档案与事实 · 全局记忆 · 冲突管理')}</p><span className="memory-badge"><Check size={12}/>{t(data.active_profile_id===engine.id+'-default'?'当前激活':'已安装')}</span></div>
      </button>)}</div>
      <div className="memory-engine-activation"><label>{t('使用的记忆空间')}<select value={reuseSpace||data.engine_spaces[engineTab]} disabled={busy||chatRunning} onChange={e=>setReuseSpace(e.target.value)}>{data.spaces.filter(s=>s.engine===engineTab&&!s.deleting).map(s=><option key={s.id} value={s.id}>{s.name}{s.is_default?' · '+t('默认空间'):''}</option>)}</select></label><button className="primary" disabled={busy||chatRunning||(data.active_profile_id===engineTab+'-default'&&(reuseSpace||data.engine_spaces[engineTab])===data.current_space_id)} onClick={()=>{const sid=reuseSpace||data.engine_spaces[engineTab];if(data.active_profile_id===engineTab+'-default'){run(()=>activate(engineTab,sid));return;}setError('');setSwitching({engine:engineTab,spaceId:sid,name:data.spaces.find(s=>s.id===sid)!.name,freshId:crypto.randomUUID().replaceAll('-','')})}}>{t(data.active_profile_id===engineTab+'-default'?'使用此空间':'激活此引擎')}</button></div>
      <form className="settings-model-form" onSubmit={e => { e.preventDefault(); run(async () => { await api('/memory/config', { method: 'PUT', body: JSON.stringify(configInput(config)) }); await overview(true); setNotice(t('记忆设置已保存，下次提问生效。')); }); }}><fieldset disabled={busy||chatRunning}>
        <legend>{engineTab==='mem0'?'Mem0 OSS':'LangMem'} · {t('引擎配置')}</legend><label className="check-label"><input type="checkbox" checked={config.enabled} onChange={e=>setConfig({...config,enabled:e.target.checked})}/>{t('启用此引擎的记忆功能')}</label><p className="field-hint">{t('关闭后暂停该引擎的记忆读取、学习和即时写入，已有记忆保留。保存后生效。')}</p>
        <label>{t('记忆提取模型')}<select value={(engineTab==='mem0'?config.mem0.model_profile_id:config.model_profile_id) || ''} onChange={e => setConfig(engineTab==='mem0'?{...config,mem0:{...config.mem0,model_profile_id:e.target.value || null}}:{ ...config, model_profile_id: e.target.value || null })}><option value="">{t('使用默认语言模型')}</option>{preferences?.profiles.filter(p => p.kind === 'chat').map(p => <option value={p.id} key={p.id}>{p.name} · {p.model}</option>)}</select></label>
        {engineTab==='langmem' && <><p className="field-hint">{t('记忆包含语义、情景与程序三层。档案固定读取，事实与经历按相关性使用，协作规则由你确认启用。')}</p><label className="check-label"><input type="checkbox" checked={config.langmem.hot_path} onChange={e=>setConfig({...config,langmem:{...config.langmem,hot_path:e.target.checked}})}/>{t('允许对话中即时写入')}</label><p className="field-hint">{t('明确说“记住、修改、不再使用”时可立即操作；锁定的记忆仍由你手动维护。此开关与后台学习独立。')}</p><label className="check-label"><input type="checkbox" checked={config.langmem.episodes} onChange={e=>setConfig({...config,langmem:{...config.langmem,episodes:e.target.checked}})}/>{t('自动整理任务经历')}</label><p className="field-hint">{t('需同时开启后台学习。只在工具操作、明确反馈或标记完成时形成经历；普通回答不等于任务成功。')}</p><label>{t('后台整理等待时间（秒）')}<input type="number" required min={0} max={300} value={config.langmem.debounce_seconds} onChange={e=>setConfig({...config,langmem:{...config.langmem,debounce_seconds:Number(e.target.value)}})}/></label><p className="field-hint">{t('默认等待 60 秒；连续提问会推迟整理，最多等待 5 分钟。每条新提问独立追踪，回答不等待整理完成。')}</p><label>{t('检索方式')}<select value={config.langmem.retrieval} onChange={e=>setConfig({...config,langmem:{...config.langmem,retrieval:e.target.value as 'keyword'|'semantic'}})}><option value="keyword">{t('关键词与偏好检索')}</option><option value="semantic">{t('语义增强检索（LangGraph Store）')}</option></select></label>{config.langmem.retrieval==='semantic'&&<><label>{t('记忆嵌入模型')}<select value={config.langmem.embedding_profile_id||''} onChange={e=>setConfig({...config,langmem:{...config.langmem,embedding_profile_id:e.target.value||null}})}><option value="">{t('使用默认嵌入模型')}</option>{preferences?.profiles.filter(p=>p.kind==='embedding').map(p=><option key={p.id} value={p.id}>{p.name} · {p.model}</option>)}</select></label><label>{t('最低相似度')}<input type="number" required min={0} max={1} step={0.05} value={config.langmem.similarity_threshold} onChange={e=>setConfig({...config,langmem:{...config.langmem,similarity_threshold:Number(e.target.value)}})}/></label></>}<p className="field-hint">{t('语义增强模式用于事实检索；任务经历融合语义、关键词、任务类型与适用条件排序。回顾历史可包含结果未确认的经历，借鉴方法只使用结果明确的经历。')}</p></>}
        {engineTab==='mem0' && <>{proceduresReady&&<><label className="checkbox-label"><input type="checkbox" checked={config.mem0.procedures!==false} onChange={e=>setConfig({...config,mem0:{...config.mem0,procedures:e.target.checked}})}/>{t('自动整理方法候选')}</label><p className="field-hint">{t('只整理明确的方法要求、纠正或有依据的经验。候选需要确认才生效；受学习记忆总开关控制。')}</p></>}<label className="checkbox-label"><input type="checkbox" checked={config.mem0.events!==false} onChange={e=>setConfig({...config,mem0:{...config.mem0,events:e.target.checked}})}/>{t('自动整理事件与经历')}</label><p className="field-hint">{t('在允许学习记忆时，整理新对话中的重要进展与结果；不回溯旧对话。需要额外模型调用。')}</p><p className="field-hint">{t('会话上下文由工作台统一管理，与长期记忆引擎分离。')}</p><label>{t('记忆嵌入模型')}<select value={config.mem0.embedding_profile_id || ''} onChange={e =>setConfig({...config,mem0:{...config.mem0,embedding_profile_id:e.target.value || null}})}><option value="">{t('使用默认嵌入模型')}</option>{preferences?.profiles.filter(p=>p.kind==='embedding').map(p=><option value={p.id} key={p.id}>{p.name} · {p.model}</option>)}</select></label><label>{t('最低相似度')}<input required type="number" min={0} max={1} step={0.05} value={config.mem0.similarity_threshold} onChange={e=>setConfig({...config,mem0:{...config.mem0,similarity_threshold:Number(e.target.value)}})}/></label><p className="field-hint">{t('无需 Mem0 云端账号。已有记忆索引与嵌入模型绑定，请保持使用建立索引时的模型。')}</p><p className="field-hint">{t('召回通常只使用向量检索和本地规则；仅在发现疑似冲突或本轮明确要求可能覆盖旧记忆时，调用记忆模型核对，不会修改已有记忆。')}</p></>}
        <p className="field-hint">{t(engineTab==='mem0'?'Mem0 原生 add 提取事实并检索旧记忆，决定 ADD、UPDATE、DELETE 或 NONE。写入边界保护锁定项，删除建议需人工处理。':'LangMem 使用结构化 Schema 提取记忆。关键词模式无需嵌入模型；语义模式通过 LangGraph Store 检索。')}</p>
        <div className="memory-global-settings"><h3>{t('本方案记忆设置')}</h3><p className="field-hint">{t('以下设置仅适用于当前配置的方案。')}</p>
        <label className="check-label"><input type="checkbox" checked={config.use_memories} onChange={e => setConfig({ ...config, use_memories: e.target.checked })}/>{t('允许使用已有记忆')}</label><label className="check-label"><input type="checkbox" checked={config.learn_memories} onChange={e => setConfig({ ...config, learn_memories: e.target.checked })}/>{t('允许从新提问自动形成记忆')}</label>

        <div className="fields"><label>{t('每轮召回条数')}<input required type="number" min={1} max={20} value={config.recall_limit} onChange={e => setConfig({ ...config, recall_limit: Number(e.target.value) })}/></label><label>{t('记忆上下文字符预算')}<input required type="number" min={500} max={12000} step={100} value={config.context_chars} onChange={e => setConfig({ ...config, context_chars: Number(e.target.value) })}/></label></div></div>
        <p className="field-hint">{t('记忆和索引保存在本机。提取与召回会调用所选模型；使用云端模型会发送相应内容并产生调用费用。')}</p><p className="field-hint">{t('目前用于普通助手和单个伙伴对话；协作流程与团队暂不接入个人记忆。')}</p>
        <div className="button-row"><button type="button" className="secondary" onClick={() => run(async () => { await api('/memory/probe', { method: 'POST', body: JSON.stringify({...configInput(config),engine:engineTab}) }); setNotice(t('测试通过：可以提取结构化记忆，测试内容未保存。')); })}>{t('测试记忆引擎')}</button><button className="primary">{busy ? t('正在处理…') : t('保存记忆设置')}</button></div>
      </fieldset></form></section> : <>
      {readOnly&&<p className="knowledge-notice">{t(currentEngine==='langmem'?'此引擎未激活，不会用于对话和后台整理；事实与偏好仍可手动管理，切回后生效。':'此引擎未激活，记忆仅供查看。请在记忆引擎页面激活后管理。')}</p>}<div className="memory-space-bar"><div className="memory-toolbar"><label><span>{t('记忆空间')}</span><span className="memory-space-select"><img src={currentEngine==='mem0'?mem0Logo:langmemLogo} alt=""/><select value={space} onChange={e=>setSpace(e.target.value)}>{data.spaces.map(s=><option value={s.id} key={s.id}>{s.engine==='mem0'?'Mem0':'LangMem'} · {s.name}{s.is_default?' · '+t('默认空间'):''}{s.is_current?' · '+t('当前使用'):''}</option>)}</select></span></label><button className="secondary" disabled={busy||chatRunning||readOnly||!!data.spaces.find(s=>s.id===space)?.is_default} onClick={()=>{setError('');setDeleting(data.spaces.find(s=>s.id===space)!);}}><Trash2 size={15}/>{t(data.spaces.find(s=>s.id===space)?.deleting?'重试删除空间':'删除空间')}</button></div><div className="memory-scheme-strip"><strong>{t('当前方案')}：{currentEngine==='mem0'?'Mem0 OSS':'LangMem'}</strong><span>{t('自动使用已有记忆')}</span><span>{currentEngine==='mem0'?t('事实、事件与方法独立整理'):t('新对话会在后台整理')}</span><button onClick={()=>{setEngineTab(currentEngine);setConfig(data.configs[currentEngine]);setTab('engine')}}>{t('查看引擎设置')} →</button></div></div><p className="field-hint memory-space-hint">{t('每个引擎的默认空间不可删除。切换引擎时可选择重新开始，建立新的独立空间。删除当前空间后，自动使用该引擎的默认空间。')}</p>
      {data.spaces.find(s=>s.id===space)?.deleting?<p role="status">{t('空间已停止使用，删除尚未完成，请重试删除。')}</p>:currentEngine==='langmem'?<LangMemWorkspace readOnly={readOnly} key={space} space={space} refreshKey={chatRunning||busy} onChanged={()=>{overview().catch(report)}} onSource={onSource}/>:<Mem0Workspace key={space} space={space} readOnly={readOnly} refreshKey={chatRunning||busy} onChanged={()=>overview().catch(report)} onSource={onSource}/>}
      <p className="field-hint memory-footnote">{t(currentEngine==='langmem'?'锁定可防止自动覆盖。删除前需要确认，删除记忆不删除原始聊天。':'手动编辑后，该条记忆由你维护，自动提取不会覆盖它。删除会停止后续召回；原始聊天记录仍然保留。')}</p>
    </>}
    {switching&&<MemorySwitchDialog engine={switching.engine==='mem0'?'Mem0':'LangMem'} spaceName={switching.name} newChat={true} locked={busy||chatRunning} error={error} onCancel={()=>setSwitching(null)} onConfirm={name=>run(()=>activate(switching.engine,switching.spaceId,name))}/>}
    {deleting&&<div className="modal-backdrop"><section className="modal small-modal" role="dialog" aria-modal="true" aria-labelledby="delete-space-title"><h2 id="delete-space-title">{t('删除记忆空间“{0}”？',deleting.name)}</h2><p>{t('将删除此空间中的记忆并停止使用，正在整理的记忆任务也会取消。原始聊天和已有备份保留。')}</p>{deleting.is_current&&<p>{t('删除后会自动使用该引擎的默认空间。')}</p>}{error&&<p role="alert" className="knowledge-error">{error}</p>}<div className="button-row"><button className="secondary" disabled={busy} onClick={()=>setDeleting(null)}>{t('取消')}</button><button className="primary" disabled={busy||chatRunning} onClick={()=>run(async()=>{await api('/memory/spaces/'+deleting.id,{method:'DELETE'});setDeleting(null);await overview();setNotice(t('记忆空间已删除。'))})}>{t(busy?'正在删除…':'确认删除空间')}</button></div></section></div>}
  </main>;
}
