import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowUpRight, Leaf, Plus, RotateCcw, Search, ShieldCheck, Users } from 'lucide-react';
import type { ConnectorSummary } from './ConnectorCatalog';
import { api } from './api';
import { t } from './i18n';
import type { Skill, SkillRef } from './SkillCatalog';
import type { Preferences } from './SettingsPage';
import type { KnowledgeBase } from './KnowledgeCenter';

export type PartnerDefinition = { execution_mode?:string; id: string; version: string; profile_version?:string; version_number?: number; name: string; description: string; source: string; customized?:boolean; instructions?: string; tool_ids: string[]; connector_tool_ids?:string[]; skill_refs?: SkillRef[]; model_profile_id?: string | null; suggested_kb_ids?: string[]; examples?: string[]; issues?: string[]; system_config?:{name:string;value:string;description:string}[] };
export const partnerVersionLabel = (p: {version: string; version_number?: number}) => p.version_number ? `v${p.version_number}` : t('历史版本');
export type Partner = PartnerDefinition & { enabled: boolean; archived?: boolean; revisions?: PartnerDefinition[] };
type Form = { name: string; description: string; instructions: string; tool_ids: string[]; connector_tool_ids?:string[]; skill_refs: SkillRef[]; model_profile_id: string | null; suggested_kb_ids: string[]; examples: string[] };
const editable = (p: Partial<PartnerDefinition>, tools: string[]): Form => ({connector_tool_ids:p.connector_tool_ids || [],name:p.name || '',description:p.description || '',instructions:p.instructions || '',tool_ids:p.tool_ids || tools,skill_refs:(p.skill_refs || []).map(({id,revision})=>({id,revision})),model_profile_id:p.model_profile_id || null,suggested_kb_ids:p.suggested_kb_ids || [],examples:p.examples || []});

export function PartnerCatalog({partners,skills,tools,connectors,onChanged,onUse,locked}: {partners:Partner[];skills:Skill[];connectors:ConnectorSummary[];tools:{id:string;name:string}[];onChanged:()=>Promise<void>;onUse:(p:PartnerDefinition)=>void;locked:boolean}) {
  const [form,setForm]=useState<Form|null>(null); const [editing,setEditing]=useState<string|null>(null);
  const [query,setQuery]=useState(''); const [archived,setArchived]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const [preferences,setPreferences]=useState<Preferences|null>(null); const [bases,setBases]=useState<KnowledgeBase[]>([]);
  useEffect(()=>{Promise.all([api<Preferences>('/settings'),api<KnowledgeBase[]>('/knowledge/bases')]).then(([p,k])=>{setPreferences(p);setBases(k);}).catch(e=>setError(e.message));},[]);
  const chosen = partners.find(p=>p.id===editing);
  const builtin = chosen?.source==='builtin';
  const update = (patch:Partial<Form>) => setForm(f=>f ? {...f,...patch}:f);
  const missingConnectorGrants = form?.connector_tool_ids?.filter(id=>!connectors.some(c=>c.tools.some(tool=>tool.id===id))) || [];
  function edit(p:Partial<PartnerDefinition>={}) {setEditing(p.id || null);setForm(editable(p,tools.map(t=>t.id)));setError('');}
  async function save(use=false) {if(!form)return;setBusy(true);setError('');try{const path=builtin?'/workbench-assistant':editing?'/partners/'+editing:'/partners';const p=await api<Partner>(path,{method:builtin?'PUT':editing?'PUT':'POST',body:JSON.stringify({...form,examples:form.examples.map(x=>x.trim()).filter(Boolean)})});await onChanged();setForm(null);if(use)onUse(p);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function changeBuiltin(path:string) {setBusy(true);setError('');try{const p=await api<Partner>(path,{method:'POST'});await onChanged();setEditing(p.id);setForm(editable(p,tools.map(t=>t.id)));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function status(p:Partner,patch:object) {setBusy(true);setError('');try{await api('/partners/'+p.id,{method:'PATCH',body:JSON.stringify(patch)});await onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="partner-catalog" aria-label={t('助手配置')}>
    {error && <div className="skill-error" role="alert">{error}</div>}
    {form ? <div className="skill-editor"><button className="back-link" disabled={busy} onClick={()=>setForm(null)}><ArrowLeft size={15}/>{t('返回助手列表')}</button><h2>{builtin?t('配置工作台助手'):editing?t('编辑助手'):t('创建助手')}</h2>{builtin&&<div className="builtin-profile-note"><ShieldCheck size={19}/><div><b>{t('内置助手 · 默认伙伴')}</b><p>{t('你可以调整个性和默认能力。核心安全、记忆和上下文规则由工作台管理。')}</p></div></div>}<p className="skill-detail-hint">{t('保存生成新版本，已有会话继续使用原配置。')}</p>
      <div className="partner-form-grid"><label className="skill-field">{t('助手名称')}<input value={form.name} maxLength={80} onChange={e=>update({name:e.target.value})}/></label><label className="skill-field">{t('默认对话模型')}<select value={form.model_profile_id || ''} onChange={e=>update({model_profile_id:e.target.value || null})}><option value="">{t('跟随工作台默认模型')}</option>{preferences?.profiles.filter(p=>p.kind==='chat').map(p=><option key={p.id} value={p.id}>{p.name} · {p.model}</option>)}{form.model_profile_id && preferences && !preferences.profiles.some(p=>p.id===form.model_profile_id) && <option value={form.model_profile_id}>{t('模型已移除')}</option>}</select></label></div>
      <label className="skill-field partner-wide">{t('助手简介')}<input maxLength={1000} value={form.description} onChange={e=>update({description:e.target.value})}/></label>
      <label className="skill-field partner-wide">{t('角色与方法')}<textarea rows={8} maxLength={12000} value={form.instructions} onChange={e=>update({instructions:e.target.value})} placeholder={t('说明助手擅长什么、如何处理任务，以及希望的回答方式。')}/></label>
      <h3>{t('绑定技能')}</h3><p className="skill-detail-hint">{t('最多绑定 3 个技能；绑定版本会随助手版本冻结。')}</p><div className="skill-tool-checks">{skills.map(s=>{const selected=form.skill_refs.find(r=>r.id===s.id);return <label key={s.id}><input type="checkbox" checked={!!selected} disabled={!selected&&(!s.enabled||s.archived||!s.compatible||form.skill_refs.length>=3)} onChange={e=>update({skill_refs:e.target.checked?[...form.skill_refs,{id:s.id,revision:s.revision}]:form.skill_refs.filter(r=>r.id!==s.id)})}/>{s.display_name}</label>;})}</div>
      {form.skill_refs.map(ref=><label className="skill-field" key={ref.id}>{skills.find(s=>s.id===ref.id)?.display_name||ref.id} · {t('技能版本')}<select value={ref.revision} onChange={e=>update({skill_refs:form.skill_refs.map(r=>r.id===ref.id?{...r,revision:e.target.value}:r)})}>{skills.find(s=>s.id===ref.id)?.revisions.map(r=><option key={r.revision} value={r.revision}>{r.version} · {r.revision.slice(0,8)}</option>)}</select></label>)}
      <h3>{t('允许使用的工具')}</h3><p className="skill-detail-hint">{t('助手与技能的授权取交集，知识库选择决定实际可用工具。')}</p><div className="skill-tool-checks">{tools.map(tool=><label key={tool.id}><input type="checkbox" checked={form.tool_ids.includes(tool.id)} onChange={e=>update({tool_ids:e.target.checked?[...form.tool_ids,tool.id]:form.tool_ids.filter(id=>id!==tool.id)})}/>{t(tool.name)}</label>)}</div>
      <h3>{t('连接器授权')}</h3><p className="skill-detail-hint">{builtin?t('选中后将限制工作台助手只能使用这些连接器；不选表示跟随每次对话的明确选择。'):t('这是助手的工具授权范围，提问时按连接器选择，仅启用范围内的工具。技能本地工具权限保持独立。')}</p><div className="skill-tool-checks">{connectors.map(connector=>{const ids=connector.tools.filter(tool=>tool.policy!=='disabled').map(tool=>tool.id);const selected=ids.some(id=>form.connector_tool_ids?.includes(id));return <label key={connector.id}><input type="checkbox" disabled={!ids.length} checked={selected} onChange={e=>update({connector_tool_ids:e.target.checked?[...new Set([...(form.connector_tool_ids || []),...ids])]:(form.connector_tool_ids || []).filter(id=>!connector.tools.some(tool=>tool.id===id))})}/>{connector.name}</label>;})}</div>{!connectors.some(c=>c.tools.some(tool=>tool.policy!=='disabled'))&&<p className="skill-detail-hint">{t('请先在连接器页面连接服务并发现工具。')}</p>}
      {!!missingConnectorGrants.length&&<p className="skill-detail-hint">{t('连接器工具已移除')}<button className="skill-text-button" onClick={()=>update({connector_tool_ids:(form.connector_tool_ids || []).filter(id=>!missingConnectorGrants.includes(id))})}>{t('移除无效授权')}</button></p>}<h3>{t('推荐知识库')}</h3><p className="skill-detail-hint">{t('只展示推荐，使用时由你明确选择，不自动接入。')}</p><div className="skill-tool-checks">{bases.map(k=><label key={k.id}><input type="checkbox" checked={form.suggested_kb_ids.includes(k.id)} onChange={e=>update({suggested_kb_ids:e.target.checked?[...form.suggested_kb_ids,k.id]:form.suggested_kb_ids.filter(id=>id!==k.id)})}/>{k.name}</label>)}</div>{!bases.length && <p className="skill-detail-hint">{t('暂无知识库，可稍后配置。')}</p>}
      <label className="skill-field partner-wide">{t('示例问题（每行一个，最多六个）')}<textarea rows={3} value={form.examples.join('\n')} onChange={e=>update({examples:e.target.value.split('\n')})}/></label>
      {builtin&&<section className="system-config-readonly"><h3><ShieldCheck size={16}/>{t('系统管理的运行配置')}</h3><p className="skill-detail-hint">{t('以下配置可查看，不会被自定义指令覆盖。')}</p><dl>{chosen?.system_config?.map(item=><div key={item.name}><dt>{t(item.name)}<span>{t(item.value)}</span></dt><dd>{t(item.description)}</dd></div>)}</dl></section>}
      <div className="button-row"><button className="primary" disabled={busy || !form.name.trim() || !form.instructions.trim()} onClick={()=>save()}>{t(builtin?'保存配置':'保存助手')}</button><button className="secondary" disabled={busy || locked || !form.name.trim() || !form.instructions.trim() || chosen?.archived || chosen?.enabled===false} onClick={()=>save(true)}>{t(builtin?'保存并新建对话试用':'保存并试用')}</button>{builtin&&<button className="secondary" disabled={busy||!chosen?.customized} onClick={()=>changeBuiltin('/workbench-assistant/reset')}><RotateCcw size={14}/>{t('恢复默认配置')}</button>}</div>
      {!!chosen?.revisions?.length && <details><summary>{t('历史配置版本')}</summary>{chosen.revisions.map(r=><details key={r.profile_version||r.version}><summary>{r.name} · {partnerVersionLabel(r)}{r.profile_version===chosen.profile_version?' · '+t('当前使用'):''}</summary><pre className="skill-source">{r.instructions}</pre><p>{t('绑定技能')}：{r.skill_refs?.map(s=>skills.find(x=>x.id===s.id)?.display_name || s.id).join(', ') || t('无')}</p><p>{t('可用工具')}：{r.tool_ids.map(id=>t(tools.find(x=>x.id===id)?.name || id)).join(', ') || t('无')}</p>{builtin&&r.profile_version!==chosen.profile_version&&<button className="secondary" disabled={busy} onClick={()=>changeBuiltin('/workbench-assistant/restore/'+r.profile_version)}>{t('恢复此版本')}</button>}</details>)}</details>}
    </div> : <><div className="skill-catalog-toolbar"><div className="skill-section-label"><h2>{t('陪你完成学习与工作')}</h2><p>{t('为不同任务配置角色、技能与工具。')}</p></div><button className="primary" onClick={()=>edit()}><Plus size={16}/>{t('创建助手')}</button></div><div className="skill-catalog-filters"><label className="tool-search"><Search size={16}/><input aria-label={t('搜索助手')} placeholder={t('搜索助手')} value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="partner-archive-toggle"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>{t('查看归档助手')}</label></div>
      <div className="partner-grid">{partners.filter(p=>!!p.archived===archived && (p.name+p.description).toLowerCase().includes(query.toLowerCase())).map(p=>{const connectorCount=connectors.filter(c=>c.tools.some(tool=>p.connector_tool_ids?.includes(tool.id))).length;return <article className="partner-card compact-capability-card" key={p.id}><div className="partner-card-top"><span className="partner-icon"><Users size={18}/></span><div className="compact-card-title"><h3>{p.source==='builtin'?t(p.name):p.name}</h3><small>{t('助手')}{(p.source!=='builtin'||p.customized)?' · '+(p.source==='builtin'?t('已定制'):partnerVersionLabel(p)):''}</small></div><span className="skill-badge">{p.source==='builtin'?t('内置'):p.archived?t('已归档'):p.enabled?t('已启用'):t('已停用')}</span>{p.source!=='builtin'&&<details className="compact-card-menu"><summary aria-label={t('更多操作')}>•••</summary><div><button disabled={busy || p.archived} onClick={()=>status(p,{enabled:!p.enabled})}>{p.enabled?t('停用'):t('启用')}</button><button disabled={busy} onClick={()=>status(p,{archived:!p.archived})}>{p.archived?t('恢复助手'):t('归档助手')}</button></div></details>}</div><p className="compact-card-description">{p.source==='builtin'?t(p.description):p.description}</p><div className="compact-card-meta"><span>{t('{0} 个技能',p.skill_refs?.length||0)}</span><span>{connectorCount?t('{0} 个连接器',connectorCount):t('无连接器')}</span></div>{p.issues?.slice(0,1).map(issue=><p className="partner-issue compact-card-issue" key={issue}>{t(issue)}</p>)}<footer><button className="secondary compact-use-button" disabled={locked || !p.enabled || p.archived} onClick={()=>onUse(p)}>{t('用于对话')}<ArrowUpRight size={13}/></button><button className="skill-text-button" onClick={()=>edit(p)}>{t('管理')}</button></footer></article>})}</div>
      <aside className="skill-examples"><div><b>{t('从一个角色开始')}</b><p>{t('模板会填入配置草稿，保存后才会创建助手。')}</p></div><div><button className="secondary" onClick={()=>edit({name:t('学习导师'),description:t('用解释、例子和自测帮助你理解知识。'),instructions:t('先了解学习目标和已有基础，分步骤解释概念，给出具体例子，再提出一道自测题。区分资料中的事实和你的解释；不确定时明确说明。'),examples:[t('请帮我理解一个新概念，并用一道题检查我的理解。')]})}><Leaf size={15}/>{t('学习导师')}</button><button className="secondary" onClick={()=>edit({name:t('资料研究员'),description:t('对照资料、比较观点，给出可核对的结论。'),instructions:t('先明确研究问题和比较维度，阅读所选知识库中的证据，区分共识、分歧和证据缺口。引用实际读取的原文，不把推测写成事实。'),examples:[t('请比较资料中的主要观点，列出依据和仍需核实的问题。')]})}>{t('资料研究员')}</button></div></aside>
    </>}
  </section>;
}
