import { usePickerState, type PickerPresentation } from './usePickerState';
import { useEffect, useRef } from 'react';
import { Check, ChevronDown, Users } from 'lucide-react';
import { t } from './i18n';
import type { Partner, PartnerDefinition } from './PartnerCatalog';
export function PartnerPicker({partners,value,locked,onChange,onManage,embedded=false,onDismiss}:PickerPresentation & {partners:Partner[];value:PartnerDefinition|null;locked:boolean;onChange:(p:PartnerDefinition)=>void;onManage:()=>void}) {
  const [open,setOpen]=usePickerState(embedded,onDismiss);const root=useRef<HTMLDivElement>(null);const trigger=useRef<HTMLButtonElement>(null);
  const builtin=partners.find(p=>p.source==='builtin');
  useEffect(()=>{if(locked)setOpen(false);},[locked]);
  useEffect(()=>{if(!open||embedded)return;const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);trigger.current?.focus();}};document.addEventListener('pointerdown',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',key);};},[open,embedded]);
  return <div className={'composer-knowledge composer-partner '+(embedded?'picker-embedded':'')} ref={root} onBlur={e=>{if(!embedded&&!e.currentTarget.contains(e.relatedTarget as Node))setOpen(false);}}>{!embedded&&<button type="button" ref={trigger} className={'knowledge-chip '+(value?'has-selection':'')} aria-label={t('选择伙伴')} aria-haspopup="dialog" aria-expanded={open} disabled={locked} onClick={()=>setOpen(!open)}><Users size={16}/><span>{value?.name || (builtin?t(builtin.name):t('工作台助手'))}</span><ChevronDown size={13}/></button>}{open && <div className="knowledge-popover" role={embedded?'region':'dialog'} aria-label={t('选择伙伴')}><header><b>{t('选择伙伴')}</b><small>{t('切换伙伴会新建对话，保留未发送的内容。')}</small></header><div className="knowledge-options">{partners.filter(p=>!p.archived).map(p=><button type="button" key={p.id} disabled={!p.enabled} onClick={()=>{onChange(p);setOpen(false);}}><Users size={18}/><span><b>{['fixed','dynamic'].includes(p.execution_mode||'')&&<small>{t(p.execution_mode==='dynamic'?'团队':'流程')}</small>}{p.source==='builtin'?t(p.name):p.name}</b><small>{!p.enabled?t('已停用'):p.source==='builtin'?t(p.description):p.description}</small></span>{(value?.id || 'workbench-assistant')===p.id && <Check size={15}/>}</button>)}</div><footer><button type="button" onClick={()=>{setOpen(false);onManage();}}>{t('管理伙伴')}</button></footer></div>}</div>;
}
