import { useEffect, useState, type ReactNode } from 'react';
import { ArrowLeft, ChevronDown, GitBranch, Plus, Play, Save } from 'lucide-react';
import { api } from './api';
import { t } from './i18n';
import type { Partner, PartnerDefinition } from './PartnerCatalog';
import type { Skill } from './SkillCatalog';
import type { ConnectorSummary } from './ConnectorCatalog';
import './workflows.css';

export type Expert = {name:string;instructions:string;partner_id?:string|null;partner_version?:string|null;tool_ids:string[];skill_refs:{id:string;revision:string}[];connector_tool_ids:string[]};
type FlowNode = {id:string;name:string;kind:'agent'|'review'|'deliver';expert:string|null;task:string;depends_on:string[];inputs:string[]|null;when:{node:string;approved:boolean}|null;rework_target:string|null;max_rework:number;timeout:number};
type FlowInput = {name:string;description:string;experts:Record<string,Expert>;nodes:FlowNode[];concurrency:number;max_model_calls:number;max_tokens:number};
type Flow = FlowInput & {id:string;version:string;version_number:number;enabled:boolean;archived:boolean};
const inputOf = (flow:FlowInput):FlowInput => ({name:flow.name,description:flow.description,experts:flow.experts,nodes:flow.nodes,concurrency:flow.concurrency,max_model_calls:flow.max_model_calls,max_tokens:flow.max_tokens});

export function WorkflowCatalog({partners,skills,connectors,tools,locked,onChanged,onUse}:{partners:Partner[];skills:Skill[];connectors:ConnectorSummary[];tools:{id:string;name:string}[];locked:boolean;onChanged:()=>Promise<void>;onUse:(p:PartnerDefinition)=>void}) {
  const [flows,setFlows]=useState<Flow[]>([]);const [templates,setTemplates]=useState<FlowInput[]>([]);
  const [draft,setDraft]=useState<FlowInput|null>(null);const [editing,setEditing]=useState<string|null>(null);
  const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [archived,setArchived]=useState(false);
  const [advanced,setAdvanced]=useState(false);const [json,setJson]=useState('');
  const load=async()=>{const [f,s]=await Promise.all([api<Flow[]>('/workflows'),api<FlowInput[]>('/workflows/templates')]);setFlows(f);setTemplates(s);};
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  function edit(flow:FlowInput,id:string|null=null){setEditing(id);setDraft(structuredClone(inputOf(flow)));setAdvanced(false);setJson(JSON.stringify(inputOf(flow),null,2));setError('');}
  async function act(fn:()=>Promise<unknown>){setSaving(true);setError('');try{await fn();await load();await onChanged();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  function expert(key:string,patch:Partial<Expert>){setDraft(d=>d?{...d,experts:{...d.experts,[key]:{...d.experts[key],...patch}}}:d);}
  function node(index:number,patch:Partial<FlowNode>){setDraft(d=>d?{...d,nodes:d.nodes.map((n,i)=>i===index?{...n,...patch}:n)}:d);}
  return <section className="workflow-catalog">
    {error&&<div className="skill-error" role="alert">{error}</div>}
    {draft?<div className="workflow-editor"><button className="back-link" disabled={saving} onClick={()=>setDraft(null)}><ArrowLeft size={15}/>{t('返回流程列表')}</button><h2>{t(editing?'编辑流程':'创建流程')}</h2><p className="skill-detail-hint">{t('阶段按依赖执行；各专家使用独立上下文，历史任务保留原版本。')}</p>
      <div className="workflow-edit-mode"><button type="button" aria-pressed={!advanced} disabled={saving} onClick={async()=>{if(!advanced)return;setSaving(true);setError('');try{setDraft(await api<FlowInput>('/workflows/validate',{method:'POST',body:json}));setAdvanced(false);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}>{t('常用配置')}</button><button type="button" aria-pressed={advanced} onClick={()=>{if(!advanced){setJson(JSON.stringify(draft,null,2));setAdvanced(true);}}}>{t('高级 JSON 配置')}</button></div>
      {advanced?<><p className="skill-detail-hint">{t('可配置阶段依赖、条件和返工目标。保存时会校验循环、引用和执行上限。')}</p><textarea className="workflow-json" aria-label={t('流程 JSON 定义')} value={json} onChange={e=>setJson(e.target.value)}/></>:<>
        <label className="skill-field">{t('流程名称')}<input value={draft.name} maxLength={80} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label className="skill-field">{t('简介')}<input value={draft.description} maxLength={1000} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
        <h3>{t('执行阶段')}</h3><div className="workflow-stage-editor">{draft.nodes.map((n,index)=><article key={n.id}><header><span>{index+1}</span><b>{n.name}</b><small>{t(n.kind==='deliver'?'程序交付':n.kind==='review'?'独立审校':'专家执行')}</small></header><label className="skill-field">{t('阶段名称')}<input value={n.name} onChange={e=>node(index,{name:e.target.value})}/></label>{n.kind!=='deliver'&&<><label className="skill-field">{t('执行专家')}<select value={n.expert || ''} onChange={e=>node(index,{expert:e.target.value})}>{Object.entries(draft.experts).map(([key,e])=><option value={key} key={key}>{e.name}</option>)}</select></label><label className="skill-field">{t('阶段任务')}<textarea rows={2} value={n.task} onChange={e=>node(index,{task:e.target.value})}/></label></>}<small>{t('前置阶段')}：{n.depends_on.map(id=>draft.nodes.find(x=>x.id===id)?.name||id).join(' → ')||t('开始')}{n.max_rework>0?' · '+t('最多返工一次'):''}</small></article>)}</div>
        <h3>{t('专家与权限')}</h3>{<ExpertFields experts={draft.experts} expert={expert} partners={partners} skills={skills} tools={tools} connectors={connectors}/>}
        <div className="partner-form-grid"><label className="skill-field">{t('最大并发')}<select value={draft.concurrency} onChange={e=>setDraft({...draft,concurrency:Number(e.target.value)})}><option value={1}>1</option><option value={2}>2</option></select></label><label className="skill-field">{t('总模型调用上限')}<input type="number" min={4} max={80} value={draft.max_model_calls} onChange={e=>setDraft({...draft,max_model_calls:Number(e.target.value)})}/></label><label className="skill-field">{t('总 Token 预算')}<input type="number" min={10000} max={500000} value={draft.max_tokens} onChange={e=>setDraft({...draft,max_tokens:Number(e.target.value)})}/></label></div>
      </>}
      <div className="button-row"><button className="primary" disabled={saving} onClick={()=>act(async()=>{const body=advanced?JSON.parse(json):draft;await api(editing?'/workflows/'+editing:'/workflows',{method:editing?'PUT':'POST',body:JSON.stringify(body)});setDraft(null);})}><Save size={15}/>{t('保存流程')}</button><button className="secondary" disabled={saving} onClick={()=>setDraft(null)}>{t('取消')}</button></div>
    </div>:<><div className="skill-catalog-toolbar"><div className="skill-section-label"><h2>{t('流程')}</h2><p>{t('让多位专家按预设阶段完成任务，查看每一步的成果与审校意见。')}</p></div><button className="skill-text-button" onClick={()=>setArchived(!archived)}>{t(archived?'查看可用流程':'查看归档流程')}</button></div>
      <div className="workflow-grid">{flows.filter(f=>f.archived===archived).map(f=><article className="workflow-card" key={f.id}><header><GitBranch size={20}/><h3>{f.name}</h3><small>v{f.version_number}</small></header><p>{f.description}</p><div className="workflow-mini-stages">{f.nodes.map(n=><span key={n.id}>{n.name}</span>)}</div><small>{t('{0} 位专家 · 最多 {1} 个阶段并行',Object.keys(f.experts).length,f.concurrency)}</small><footer><button className="primary" disabled={locked||saving||!f.enabled||f.archived} onClick={()=>{const p=partners.find(p=>p.id===f.id);if(p)onUse(p);}}><Play size={13}/>{t('用于对话')}</button><button className="skill-text-button" onClick={()=>edit(f,f.id)}>{t('编辑')}</button><button className="skill-text-button" disabled={saving} onClick={()=>act(()=>api('/workflows/'+f.id,{method:'PATCH',body:JSON.stringify(f.archived?{archived:false}:{enabled:!f.enabled})}))}>{t(f.archived?'恢复':f.enabled?'停用':'启用')}</button>{!f.archived&&<button className="skill-text-button" disabled={saving} onClick={()=>act(()=>api('/workflows/'+f.id,{method:'PATCH',body:JSON.stringify({archived:true})}))}>{t('归档')}</button>}</footer></article>)}</div>
      {!archived&&<><h3 className="workflow-template-title">{t('从示例开始')}</h3><div className="workflow-templates">{templates.map((template,index)=><button key={index} onClick={()=>edit(template)}><Plus size={18}/><span><b>{t(template.name)}</b><small>{t(template.description)}</small></span></button>)}</div></>}
    </>}
  </section>;
}

export type WorkflowRun = {run_id:string;name:string;status:string;plan?:{version:number;hash:string};execution_mode?:string;quality:string;usage:{model_calls:number;usage_tokens:number;usage_unknown:boolean};nodes:FlowNode[];stages:{node_id:string;name:string;kind:string;expert:string;expert_name?:string;attempt:number;status:string;failures?:{time:string;error:string}[];exhausted?:boolean;blocked_by?:string[];artifact_version?:number;output_hash?:string;output:string;error:string;approved:boolean|null;budget?:{reason:string;used_tokens:number;max_tokens:number;model_calls:number;max_model_calls:number;next_reservation:number;usage_unknown:boolean}|null;feedback?:string;artifact?:string;records:{tool:string;status:string;result:string}[]}[]};
export function WorkflowRunCards({runs,renderMarkdown}:{runs:WorkflowRun[];renderMarkdown:(s:string)=>ReactNode}) {
  const status:Record<string,string>={rejected:t('已取消操作'),conflict:t('操作需核对'),pending:t('等待前置阶段'),running:t('进行中'),interrupted:t('已中断，可继续'),completed:t('已完成'),skipped:t('条件未满足，已跳过'),failed:t('未完成'),stopped:t('已停止'),limited:t('已达本轮上限'),waiting_approval:t('待确认'),superseded:t('已由返工轮次替代')};
  return <div className="workflow-runs">{runs.map(run=><section key={run.run_id} className="workflow-run"><header><GitBranch size={16}/><b>{run.name}</b><small>{run.usage.model_calls} {t('次模型调用')}</small></header>{run.plan&&<p className="workflow-usage">{t('任务计划')} · v{run.plan.version} · {run.plan.hash.slice(0,8)}<br/>{t('计划已保存，恢复时仅继续未完成任务。')}</p>}{run.quality==='needs_review'&&<p className="workflow-warning">{t('返工已达上限，交付内容仍需人工检查。')}</p>}<div className="workflow-run-stages">{run.nodes.map(node=>{const attempts=run.stages.filter(s=>s.node_id===node.id);const latest=attempts.at(-1);return <details key={node.id} className={'workflow-run-stage '+latest?.status}><summary><i/><span>{node.name}</span><small>{status[latest?.status||'pending']||latest?.status}</small><ChevronDown size={13}/></summary><p className="workflow-dependencies">{t('前置阶段')}：{node.depends_on.map(id=>run.nodes.find(n=>n.id===id)?.name||id).join('、')||t('开始')}</p>{node.task&&<p className="workflow-dependencies">{node.task}</p>}{attempts.map(stage=><div className="workflow-attempt" key={stage.attempt}><p><b>{t('第 {0} 次执行',stage.attempt)}</b> · {stage.expert_name||stage.expert||t('程序交付')}{stage.approved!==null?' · '+t(stage.approved?'审校通过':'审校未通过'):''}</p>{!!stage.failures?.length&&<p className="workflow-warning">{t('已记录 {0} 次失败',stage.failures.length)}{stage.exhausted?' · '+t('重试已达上限，请新建对话'):''}</p>}{!!stage.blocked_by?.length&&<p>{t('等待前置任务完成')}</p>}{stage.error&&<p role="alert" className="workflow-warning">{t(stage.error)}</p>}{stage.budget&&<p className="workflow-warning">{t('已计入 {0} / {1} tokens，模型调用 {2} / {3} 次。',stage.budget.used_tokens.toLocaleString(),stage.budget.max_tokens.toLocaleString(),stage.budget.model_calls,stage.budget.max_model_calls)}{stage.budget.reason==='tokens'&&<><br/>{t('下一次调用预计需预留 {0} tokens（含最大输出）；预估不等于实际消费。',stage.budget.next_reservation.toLocaleString())}</>}{stage.budget.usage_unknown&&<><br/>{t('包含尚未取得实际用量的调用预留。')}</>}</p>}{stage.output&&<div className="markdown">{renderMarkdown(stage.kind==='review'&&stage.feedback?stage.feedback:stage.output)}</div>}{stage.artifact&&<p>{t('成果文件')}：{stage.artifact}</p>}{!!stage.records.length&&<details><summary>{t('工具调用记录')} · {stage.records.length}</summary>{stage.records.map((r,i)=><details key={i}><summary>{r.tool} · {r.status}</summary><pre>{r.result}</pre></details>)}</details>}</div>)}</details>;})}</div><p className="workflow-usage">{run.usage.usage_tokens.toLocaleString()} tokens · {t(run.usage.usage_unknown?'包含保守估算':'供应商返回用量')}</p></section>)}</div>;
}

export function ExpertFields({experts,expert,partners,skills,tools,connectors,onRemove}:{onRemove?:(key:string)=>void;experts:Record<string,Expert>;expert:(key:string,patch:Partial<Expert>)=>void;partners:Partner[];skills:Skill[];tools:{id:string;name:string}[];connectors:ConnectorSummary[]}) {return <>{Object.entries(experts).map(([key,e])=><details className="workflow-expert" key={key}><summary>{key==='leader'?t('团长')+' · ':''}{e.name}</summary>{onRemove&&key!=='leader'&&<button type="button" className="skill-text-button" onClick={()=>onRemove(key)}>{t('移除此成员')}</button>}<label className="skill-field">{t('引用已有助手')}<select value={e.partner_id || ''} onChange={event=>{const p=partners.find(p=>p.id===event.target.value);expert(key,{partner_id:p?.id || null,partner_version:p?.version || null,name:p?.name || e.name});}}><option value="">{t('使用独立角色配置')}</option>{partners.filter(p=>p.source!=='builtin'&&!['fixed','dynamic'].includes(p.execution_mode||'')&&!p.archived&&p.enabled).map(p=><option key={p.id} value={p.id}>{p.name} · v{p.version_number}</option>)}</select></label>{e.partner_id?<p className="skill-detail-hint">{t('运行时使用引用版本的角色、技能与工具权限，模型沿用对话选择。')}</p>:<><label className="skill-field">{t('名称')}<input value={e.name} onChange={event=>expert(key,{name:event.target.value})}/></label><label className="skill-field">{t('角色与方法')}<textarea rows={3} value={e.instructions} onChange={event=>expert(key,{instructions:event.target.value})}/></label><p className="skill-detail-hint">{t('最多绑定 3 个技能')}</p><div className="skill-tool-checks">{skills.filter(s=>s.enabled&&!s.archived&&s.compatible).map(s=>{const selected=e.skill_refs?.some(r=>r.id===s.id);return <label key={s.id}><input type="checkbox" checked={selected} disabled={!selected&&(e.skill_refs?.length||0)>=3} onChange={event=>expert(key,{skill_refs:event.target.checked?[...(e.skill_refs||[]),{id:s.id,revision:s.revision}]:(e.skill_refs||[]).filter(r=>r.id!==s.id)})}/>{s.display_name}</label>;})}</div><div className="skill-tool-checks">{tools.map(tool=><label key={tool.id}><input type="checkbox" checked={e.tool_ids.includes(tool.id)} onChange={event=>expert(key,{tool_ids:event.target.checked?[...e.tool_ids,tool.id]:e.tool_ids.filter(id=>id!==tool.id)})}/>{t(tool.name)}</label>)}</div><p className="skill-detail-hint">{t('允许使用的连接器；提问时仍需选择，且只纳入当前已授权工具。')}</p><div className="skill-tool-checks">{connectors.map(c=>{const ids=c.tools.filter(tool=>tool.policy!=='disabled').map(tool=>tool.id);return <label key={c.id}><input type="checkbox" disabled={!ids.length} checked={ids.length>0&&ids.every(id=>e.connector_tool_ids.includes(id))} onChange={event=>expert(key,{connector_tool_ids:event.target.checked?[...new Set([...e.connector_tool_ids,...ids])]:e.connector_tool_ids.filter(id=>!c.tools.some(tool=>tool.id===id))})}/>{c.name}</label>;})}</div></>}</details>)}</>;}
