import { useEffect, useState } from 'react';
import { AlertTriangle, Brain, CheckCircle2, ChevronDown, CircleMinus, Pencil, RefreshCw, X, LockKeyhole } from 'lucide-react';
import { api } from './api';
import { t } from './i18n';
import './working-memory.css';
type Fields={goal:string;constraints:string[];decisions:string[];pending:string[];next_steps:string[]};
type Task={fields?:Fields;version?:number;status?:string;locked?:boolean;origin?:string;error?:string;references?:Record<string,string>[]};
type ContextCheck={id:string;label:string;status:'pass'|'warning'|'fail'|'not_applicable';message:string};
type ContextLayer={id:string;label:string;policy:string;required:boolean;budget_tokens:number;used_tokens:number;original_tokens:number;source_count:number;truncated:boolean;status:string};
type ContextAudit={schema_version:string;status:'healthy'|'warning'|'error'|'empty';score:number;checks:ContextCheck[];metrics:{context_window:number;capacity_known:boolean;input_capacity:number;estimated_input:number;usage_percent:number;unallocated_tokens:number;raw_messages:number;usable_messages:number;compressed_messages:number;level1_segments:number;level2_core:boolean;externalized_results:number;history_searches:number;history_reads:number;history_tool_calls:number;excluded_turns:number;model_calls:number;tool_calls:number;usage_tokens:number;usage_unknown:boolean};layers:ContextLayer[]};
export type WorkingContext={request_summary?:{text?:string};task_state?:Task;running_summary?:{text?:string;version?:number;source_ids?:string[];levels?:{raw?:number;segments?:number;core?:number}};context_budget?:{context_window?:number;input_capacity?:number;estimated_input?:number;unallocated_tokens?:number;output_reserve?:number;safety_margin?:number;fixed_tokens?:number;history_tokens?:number;tool_tokens?:number;layer_version?:string;compression?:{raw_messages?:number;level1_segments?:number;level2_core?:boolean;compressed_messages?:number};layers?:ContextLayer[];trimmed_tool_ids?:string[];compressed_user_ids?:string[];degraded?:boolean};audit?:ContextAudit;error?:string;notice?:string;diagnostic?:Record<string,unknown>};
const empty:Fields={goal:'',constraints:[],decisions:[],pending:[],next_steps:[]};
export function WorkingMemoryPanel({threadId,data,busy,onChanged}:{threadId:string;data:WorkingContext;busy:boolean;onChanged:()=>Promise<unknown>}) {
 const [open,setOpen]=useState(false),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [audit,setAudit]=useState<ContextAudit|undefined>(data.audit),[auditLoading,setAuditLoading]=useState(false);
 const [fields,setFields]=useState<Fields>(empty),[locked,setLocked]=useState(true),[status,setStatus]=useState('active'),[version,setVersion]=useState(0);
 const [sources,setSources]=useState<{items:{id:string;role:string;content:string;tool_calls?:unknown}[];page:number;total:number;excluded_turn_ids?:string[]}|null>(null),[sourceKind,setSourceKind]=useState('summary');
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!saving){setEditing(false);setSources(null);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[saving]);
 useEffect(()=>setAudit(data.audit),[data.audit]);
 const task=data.task_state||{},summary=data.running_summary||{},budget=data.context_budget||{};
 const labels:Record<keyof Omit<Fields,'goal'>,string>={constraints:t('关键约束'),decisions:t('已作决定'),pending:t('待解决问题'),next_steps:t('下一步')};
 const states:Record<string,string>={active:t('进行中'),paused:t('已暂停'),completed:t('用户确认完成')};
 const run=async(fn:()=>Promise<unknown>)=>{setError('');setSaving(true);try{await fn();}catch(e){setError((e as Error).message);}finally{setSaving(false);}};
 const sourcePage=async(page:number,kind=sourceKind)=>{setSourceKind(kind);setSources(await api(`/sessions/${threadId}/working-memory/sources?page=${page}&kind=${kind}`));};
 const refreshAudit=async()=>{setError('');setAuditLoading(true);try{setAudit(await api(`/sessions/${threadId}/working-memory/audit`));}catch(e){setError((e as Error).message);}finally{setAuditLoading(false);}};
 return <div className="working-memory"><button type="button" className="working-toggle" aria-expanded={open} onClick={()=>setOpen(!open)}><Brain size={16}/><b>{t('当前任务')}</b><span>{task.fields?.goal||t('会话工作记忆')}</span>{task.locked&&<LockKeyhole size={13}/>}<small>{states[task.status||'active']}</small><ChevronDown size={15}/></button>
 {open&&<section className="working-body" aria-label={t('会话工作记忆')}><div className="working-heading"><div><b>{t('只在本次对话中使用')}</b><p>{t('任务字段仅用于本次会话；可观察操作与结果可另外整理为任务经历。')}</p></div><button disabled={busy||saving} onClick={()=>{setFields(task.fields||empty);setLocked(true);setVersion(task.version||0);setStatus(task.status||'active');setEditing(true);}}><Pencil size={14}/>{t('修订任务')}</button></div>
 {(error||data.error||task.error)&&<p className="working-error" role="alert">{t(error||data.error||task.error||'')}</p>}<p className="working-goal">{task.fields?.goal||t('下一轮回答后会整理任务状态，也可以手动填写。')}</p>
 <div className="working-grid">{Object.entries(labels).map(([key,label])=><div key={key}><h3>{label}</h3>{task.fields?.[key as keyof Omit<Fields,'goal'>]?.length?<ul>{task.fields[key as keyof Omit<Fields,'goal'>].map((line,i)=><li key={i}>{line}</li>)}</ul>:<p className="working-muted">{t('尚未记录')}</p>}</div>)}</div>
 {!!task.references?.length&&<details><summary>{t('关联资料')}</summary>{task.references.map((r,i)=><p key={i} className="working-reference">{Object.values(r).join(' · ')}</p>)}</details>}
 <details className="working-summary"><summary>{t('三级历史压缩')} · {summary.text?t('版本 {0} · 核心 {1} · 阶段 {2} · 近期原文 {3}',summary.version||0,summary.levels?.core||0,summary.levels?.segments||0,summary.levels?.raw||0):t('尚未压缩')}</summary><p className="working-muted">{t('较早内容整理为核心摘要和阶段摘要，近期消息保留原文。压缩内容不能代替事实来源，全部原文仍可核对。')}</p><pre>{summary.text||t('较短的对话直接使用原文，接近上下文预算时自动建立阶段摘要和核心摘要。')}</pre><div className="working-actions"><button disabled={busy||saving} onClick={()=>run(async()=>{await api(`/sessions/${threadId}/working-memory/rebuild`,{method:'POST',body:JSON.stringify({version:summary.version||0})});await onChanged();})}><RefreshCw size={14}/>{saving?t('正在处理…'):t('从原文重建摘要')}</button><button disabled={saving} onClick={()=>run(()=>sourcePage(1,'summary'))}>{t('查看摘要来源')}</button></div></details>
 {budget.context_window&&<details className="working-budget"><summary>{t('上下文预算')} · {t('保守估算 {0} / {1} Token',budget.estimated_input||0,budget.context_window)}</summary><div className="working-budget-bar"><i style={{width:Math.min(100,100*((budget.estimated_input||0)+(budget.output_reserve||0))/(budget.context_window||1))+'%'}}/></div><p>{t('固定上下文 {0} · 其中工具定义 {1} · 会话 {2} · 回答预留 {3} · 安全余量 {4}',budget.fixed_tokens||0,budget.tool_tokens||0,budget.history_tokens||0,budget.output_reserve||0,budget.safety_margin||0)}</p><p className="working-muted">{t('显示最近一次回答请求的预算。按 UTF-8 字节保守估算，并非账单 Token；更换模型后下一轮重新计算。')}</p>{!!budget.compressed_user_ids?.length&&<><p>{t('本轮超长问题已分段整理；模型使用派生摘要，细节可查看原文。')}</p><pre>{data.request_summary?.text}</pre></>}{!!budget.trimmed_tool_ids?.length&&<p>{t('本次上下文包含工具结果节选，完整结果可在原始记录查看。')}</p>}</details>}
 {audit&&<details className="working-audit"><summary><span className={'audit-state '+audit.status}>{audit.status==='healthy'?<CheckCircle2 size={14}/>:audit.status==='error'?<AlertTriangle size={14}/>:<CircleMinus size={14}/>} {t(audit.status==='healthy'?'上下文健康':'上下文需要检查')}</span><span>{t('诊断得分 {0}',audit.score)}</span></summary><div className="audit-overview"><div><b>{audit.metrics.capacity_known?audit.metrics.usage_percent+'%':'—'}</b><span>{t('输入容量')}</span></div><div><b>{audit.metrics.compressed_messages}</b><span>{t('已压缩消息')}</span></div><div><b>{audit.metrics.externalized_results}</b><span>{t('大型结果')}</span></div><div><b>{audit.metrics.history_tool_calls}</b><span>{t('历史回查')}</span></div></div><div className="audit-checks">{audit.checks.map(check=><div key={check.id} className={'audit-check '+check.status}>{check.status==='pass'?<CheckCircle2 size={15}/>:check.status==='fail'||check.status==='warning'?<AlertTriangle size={15}/>:<CircleMinus size={15}/>}<span><b>{t(check.label)}</b><small>{t(check.message)}</small></span></div>)}</div>{!!audit.layers.length&&<details className="audit-layers"><summary>{t('查看本轮上下文分层')}</summary>{audit.layers.map(layer=><div key={layer.id}><span>{t(layer.label)}</span><small>{layer.used_tokens} / {layer.budget_tokens} · {t(layer.truncated?'已截断':layer.status==='included'?'已纳入':'未使用')}</small></div>)}</details>}<div className="working-actions"><button disabled={auditLoading} onClick={refreshAudit}><RefreshCw size={14}/>{auditLoading?t('正在处理…'):t('重新检查')}</button><small>{t('诊断仅保存指标和来源校验结果，不复制聊天与工具正文。')}</small></div></details>}
 <div className="working-actions"><button disabled={saving} onClick={()=>run(()=>sourcePage(1,'all'))}>{t('查看完整会话原文')}</button><button disabled={saving} onClick={()=>run(()=>sourcePage(1,'task'))}>{t('查看任务整理来源')}</button><small>{task.origin==='manual'?t('手动修订'):t('自动整理，供核对')}{task.locked?' · '+t('已锁定'):''}</small></div></section>}
 {editing&&<div className="modal-backdrop"><form className="modal working-edit" role="dialog" aria-modal="true" aria-label={t('修订任务')} onSubmit={e=>{e.preventDefault();run(async()=>{const clean={...fields};for(const k of Object.keys(labels))clean[k as keyof Omit<Fields,'goal'>]=fields[k as keyof Omit<Fields,'goal'>].filter(x=>x.trim());await api(`/sessions/${threadId}/working-memory/task`,{method:'PUT',body:JSON.stringify({...clean,version,locked,status})});await onChanged();setEditing(false);});}}><h2>{t('修订任务')}</h2><label>{t('当前目标')}<textarea required maxLength={600} value={fields.goal} onChange={e=>setFields({...fields,goal:e.target.value})}/></label>{Object.entries(labels).map(([key,label])=><label key={key}>{label}<textarea value={fields[key as keyof Omit<Fields,'goal'>].join('\n')} onChange={e=>setFields({...fields,[key]:e.target.value.split('\n')})}/></label>)}<p className="working-muted">{t('列表每行一项，每项最多 300 字符。')}</p><label>{t('任务状态')}<select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(states).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="working-check"><input type="checkbox" checked={locked} onChange={e=>setLocked(e.target.checked)}/>{t('锁定任务内容，停止自动改写')}</label>{error&&<p role="alert" className="working-error">{t(error)}</p>}<div className="working-actions"><button type="button" disabled={saving} onClick={()=>setEditing(false)}>{t('取消')}</button><button disabled={busy||saving} className="primary">{t('保存任务状态')}</button></div></form></div>}
 {sources&&<div className="modal-backdrop"><section className="modal working-sources" role="dialog" aria-modal="true" aria-label={t('会话原文')}><div className="working-heading"><h2>{t('会话原文')}</h2><button aria-label={t('关闭')} onClick={()=>setSources(null)}><X size={18}/></button></div><p className="working-muted">{t('包含用户消息、助手消息和工具结果，摘要本身不作为独立证据。')}</p><p className="working-muted">{t('排除一轮会保留聊天原文，清空当前任务状态和旧摘要（含手动修订）；后续工作记忆不再使用该轮。已写入的长期记忆需单独管理。')}</p>{error&&<p className="working-error" role="alert">{t(error)}</p>}{sources.items.map(m=><article key={m.id}><b>{({human:t('你'),ai:t('工作台'),tool:t('工具结果')} as Record<string,string>)[m.role]||m.role}</b><small>{m.id}</small>{m.role==='human'&&<button disabled={busy||saving} onClick={()=>run(async()=>{await api(`/sessions/${threadId}/working-memory/exclusion`,{method:'PUT',body:JSON.stringify({turn_id:m.id,task_version:task.version||0,excluded:!sources.excluded_turn_ids?.includes(m.id),version:summary.version||0})});await onChanged();await sourcePage(sources.page);})}>{sources.excluded_turn_ids?.includes(m.id)?t('恢复为工作记忆来源'):t('从工作记忆排除这一轮')}</button>}<pre>{m.content}</pre>{Array.isArray(m.tool_calls)&&m.tool_calls.length>0&&<pre>{JSON.stringify(m.tool_calls,null,2)}</pre>}</article>)}{!sources.total&&<p>{t('暂无来源记录')}</p>}<div className="working-actions"><button disabled={saving||sources.page<=1} onClick={()=>run(()=>sourcePage(sources.page-1))}>{t('上一页')}</button><span>{sources.page} / {Math.max(1,Math.ceil(sources.total/10))}</span><button disabled={saving||sources.page*10>=sources.total} onClick={()=>run(()=>sourcePage(sources.page+1))}>{t('下一页')}</button></div></section></div>}
 </div>;
}
